### ISSUE TITLE
Typo? Conjugations page

### ISSUE THREAD

**Issue by kuzminrobin** [MicrosoftDocs/quantum-docs#104]
On [this page ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/statements/conjugations#conjugations)I see:
> and the control is returned to the **callee**

I expected:
> and the control is returned to the **caller**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a6fc97-7613-1c68-e16e-8acef47c7ab6
* Version Independent ID: 384cf707-b535-4669-8674-de4dda91faa2
* Content: [Conjugations in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/statements/conjugations#conjugations)
* Content Source: [articles/user-guide/language/Statements/conjugations.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Statements/conjugations.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by geduardo** [comment]
Yes, good catch. I fixed it in this PR: https://github.com/microsoft/qsharp-language/pull/90

**Comment by cjgronlund** [comment]
Issue resolved. @Bradben to review and merge PR.
