### ISSUE TITLE
IQ# Magic commands list is outdated

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#106]
This page has a manually edited list of IQ# commands, and it looks like it diverged from the automatically generated list at https://docs.microsoft.com/en-us/qsharp/api/iqsharp-magic/. At a glance, several of the missing commands are `%azure.quotas`, `%trace` and `%debug`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc66ff43-2536-a6f6-a7c0-464b3ce95c5e
* Version Independent ID: 18740ea8-a9c7-3911-5c4b-a1cc6f220875
* Content: [IQ# Magic Commands - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/quickref/iqsharp)
* Content Source: [articles/user-guide/quickref/iqsharp.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/quickref/iqsharp.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec**

**Comment by dime10** [comment]
Good catch!

@geduardo Should we keep the article in this form? It manually duplicates the commands from the API reference with slightly different explanatory sentences.

**Comment by geduardo** [comment]
I think we can remove this article since it's basically a duplicate. What do you think @tcNickolas @dime10?

**Comment by cgranade** [comment]
+@anjbur
