### ISSUE TITLE
Samples link for IonQ/Honeywell quickstarts point to QIO samples repo

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#107]
Both [IonQ quickstart](https://docs.microsoft.com/en-us/azure/quantum/quickstart-ionq) and [Honeywell quickstart](https://docs.microsoft.com/en-us/azure/quantum/quickstart-honeywell) "Next Steps" sections suggest to check out the samples directory. The link in both points to https://github.com/microsoft/qio-samples, samples for optimization service, rather than samples of code to run on quantum hardware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1775853-0893-a1b2-232d-33388449f176
* Version Independent ID: 39411385-816e-b60a-d268-cb782163b5aa
* Content: [Honeywell quickstart for Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-honeywell#next-steps)
* Content Source: [articles/quickstart-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-honeywell.md)
* Service: **azure-quantum**
* Sub-service: **computing**
* GitHub Login: @mblouin
* Microsoft Alias: **mblouin**

**Comment by dime10** [comment]
Thank you @tcNickolas for pointing this out. I will change it to the proper destination.
