### ISSUE TITLE
ResourcesEstimator documentation doesn't reflect latest changes

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs#11]
The new version of the `ResourcesEstimator` also outputs a column `Max` that we don't have documentation for.
https://docs.microsoft.com/en-us/quantum/user-guide/machines/resources-estimator

**Comment by dime10** [comment]
Commit `6eb9d45dce1a875ec7ce8edfb21b9301a417caf9` over on https://github.com/microsoft/qsharp-runtime contains the changes you reference.

When using the ResourceEstimator programmatically, the resource counts are not reset between calls to the same estimator instance. The results are thus accumulated in the `Sum` column (this behaviour was already the case previously). The new behaviour now adds the `Max` column, which contains the maximum value encountered for each resource up to this point.

**Comment by geduardo** [comment]
Yes (this is the PR if you want to take a look: https://github.com/microsoft/qsharp-runtime/pull/264). But in a previous conversation with the author of the PR I didn't completely understand one thing.

This is an excerpt of our conversation:

> It's very common for a Q# program to consist of multiple operations with a complicated call-graph between them, but no operation-level metrics will be collected for them when the entry-point operation is run by the simulator (that is, numbers in both columns will be the same). My change addressed the case when the user runs independent Q# operations against the same simulator sequentially.

My doubts are: What is exactly an independent Q# operation and how can be run sequentially? I'd ask her directly but I think she left the team.

**Comment by dime10** [comment]
I believe this refers to using the resource estimator from a C# program, where you would specify a specific Q# operation to run the estimator on (doesn't need to be the entry point). The [linked issue](https://github.com/microsoft/qsharp-runtime/issues/189) contains an example where the estimator is run on two separate operations. I think independent here means that the operations don't call one another.

**Comment by geduardo** [comment]
Oh, I think I understand it now. Thanks, @dime10, that issue was very clarifying. Btw, I've been running some experiments and the Python version of the resources estimator works a bit differently. I'm preparing a PR.
