### ISSUE TITLE
 qubit not released

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs#114]
Hi,
In the first Q# snippet of this page, I don't think that the qubit is released when the Hadamard gate is applied.
I suspect that it comes from the 'using' to 'use' update : previously curly brackets were here to release the qubit.
Best 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: efb42ceb-2ded-bda8-90b7-e7eba5d6bfff
* Version Independent ID: 4ed13811-8ad5-556c-af72-049400d14a5c
* Content: [Invalidated qubits use checker - Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/fr-fr/azure/quantum/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker)
* Content Source: [articles/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @vadym-kl
* Microsoft Alias: **vadym**

**Comment by geduardo** [comment]
Hi @vivienlonde, you're right, good catch! According to [this](https://github.com/microsoft/qsharp-language/blob/main/Approved/1-implicitly-scoped-qubit-allocation.md#proposed-modification), adding the curly braces back should fix it.

**Comment by geduardo** [comment]
I'll open a PR to change it.

**Comment by vivienlonde** [comment]
Thanks !
