### ISSUE TITLE
'while' keyword not colored in codeblocks

### ISSUE THREAD

**Issue by gillenhaalb** [MicrosoftDocs/quantum-docs#12]
The `while` keyword isn't being colored in the codeblocks where it's used. 
See https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/control-flow?view=qsharp-preview#while-loop

We've encountered something similar with other keywords in the past, but I forget if this repo is the proper spot for the issue. Anyone know the approach for this (or who to contact)?

**Comment by geduardo** [comment]
This didn't work: https://github.com/DuncanmaMSFT/highlight.js/pull/33

@Bradben @cjgronlund do you know how could we solve this? Apparently is occurring as well with other new keywords like `use` and `borrow`.

**Comment by cjgronlund** [comment]
@geduardo: I've assigned a work item to @Bradben to investigate this. I'm closing this issue and will track via Azure DevOps.

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1829951
