### ISSUE TITLE
Document running non-Notebook Q# code on Binder

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#120]
It is possible to run on Binder not only Q# Notebooks, but also regular Q# projects that use command line. (Open the terminal and enter whatever command you need.) It is really hard to figure out, though - I only figured it out recently. I think this is a really good ability to highlight in the documentation, since zero-install experience is probably the most frequently asked for feature.

As a side note, would it make sense to also mention using Binder with the Quantum Katas on the same page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9440da1-5c63-305b-38c2-dd1672689174
* Version Independent ID: 8e378ba7-1ce3-6faf-8c65-71652a5db445
* Content: [Develop with Q# and Binder - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-binder-qdk)
* Content Source: [articles/install-binder-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-binder-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by cgranade** [comment]
Jupytext is also enabled on Binder, allowing you to run command-line applications with PowerShell notebooks by using the typical Ctrl+Enter keybinding to run cells. For example, on the CHSH game's README.md: 

![image](https://user-images.githubusercontent.com/31516/114631519-929e0880-9c71-11eb-8b7d-81ae238af7e8.png)

**Comment by tcNickolas** [comment]
Yes, this too! I didn't know it's possible either

**Comment by dime10** [comment]
Hi @tcNickolas I'm taking a look a this. I have two questions regarding your suggestion:

- You mention a zero-install experience, don't the Q# notebooks and Q# python notebooks provide such an experience?
- To open a new terminal, did you click on `create a new command line terminal` from the binder-index notebook? For me this attempts to open a terminal on localhost which would require a local Jupyter installation.

@cgranade Thanks for the information! Do you know of a use case for the feature you mention? I imagine running a sample without being able to see and/or modify the code might not be as useful.

**Comment by tcNickolas** [comment]
@dime10 

* Indeed, Q# notebooks on Binder provide such experience, *for Q# code that is implemented as a notebook or has a notebook frontend*. For Q# code that is framed as Q# project, without Jupyter Notebook frontend, zero-install experience is not documented, while it exists. The case in hand is https://github.com/quantumcoalition/qchack-microsoft-challenge - you'll see that the Hackathon tasks are not framed as notebooks, but it was still very useful for the attendees to run the Q# project code on Binder.
* I used New -> Terminal from the root of the enlistment (see screenshot), and it opens a terminal on Binder - that terminal and my local setup have different versions of IQ# installed, so they are not the same environment.
![image](https://user-images.githubusercontent.com/10113024/116127177-61173b00-a67c-11eb-89b8-e3ae53179e78.png)
You can edit and save files in a similar manner too, so it's possible to do some work this way, not just run existing code.

**Comment by cgranade** [comment]
> @cgranade Thanks for the information! Do you know of a use case for the feature you mention? I imagine running a sample without being able to see and/or modify the code might not be as useful.

No worries, happy to help! You can definitely see and modify the code with that flow, by opening the code as Jupyter Notebook tabs. That doesn't give all the nice editing experience that you would get from a GH Codespaces environment, but it's still helpful. In particular, it's another way of running samples without Notebook interfaces, as per @tcNickolas' comment above, that may be more natural some users (less natural for others, such that both workflows may be reasonable — not trying to make a direct comparison here).
