### ISSUE TITLE
ParallelTempering target docs

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#122]
In the documentation for `Provider: Microsoft QIO` > `Parallel Tempering` the docs state that "This target can be run on CPU or FPGA hardware." however it should be CPU only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a30e2e-dd34-0d44-14d3-3ea59bae7ada
* Version Independent ID: c512826e-37d3-c3f9-5ae1-297f43dceb8a
* Content: [List of targets on Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/reference-target-list#feedback)
* Content Source: [articles/reference-target-list.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/reference-target-list.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @geduardo
* Microsoft Alias: **kitty**

**Comment by frtibble** [comment]
tagging @geduardo @dime10

**Comment by dime10** [comment]
Thanks for bringing this up @frtibble!
