### ISSUE TITLE
Sign in the number operator

### ISSUE THREAD

**Issue by nikospetropo** [MicrosoftDocs/quantum-docs#124]
Hi, I was just running the operators in Mathematica and I noticed that in the number operator you have a (-) sign while it should be (+). That is:

n=(1+Z_j)/2

Cheers!

**Comment by geduardo** [comment]
Hi @nikospetropo, thanks for filling the issue. Could you specify which article?

**Comment by nikospetropo** [comment]
Hello,

Yes it's in the Jordan Wigner decomposition:
https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/concepts/jordan-wigner#constructing-hamiltonians-in-jordan-wigner-representation

Thank you for your reply to my inquiry; I hope it proves to be useful.

Best,
Nikos Petropoulos

**Comment by geduardo** [comment]
Thanks, @nikospetropo, the formula that's shown in the article is correct with the convention defined in the article. See the note:
![image](https://user-images.githubusercontent.com/48300381/115034798-2e2ab580-9ecc-11eb-97ef-89e2873ceb9f.png)

To see it, take the definitions of the creation and anhiliation operators and calculate:

![image](https://user-images.githubusercontent.com/48300381/115035490-eb1d1200-9ecc-11eb-9b14-235ee5fddb24.png)
![image](https://user-images.githubusercontent.com/48300381/115036640-fe7cad00-9ecd-11eb-9ca0-a71aa72f9328.png)

Using the fact that: 

![image](https://user-images.githubusercontent.com/48300381/115035987-6088e280-9ecd-11eb-831e-5f58ffad57d6.png)

You can get that:

![image](https://user-images.githubusercontent.com/48300381/115036236-9d54d980-9ecd-11eb-9d62-92b9882d77fd.png)

That is the formula given in the article.

In other conventions, the sign of the Z_j might vary depending on which states you associate with the positive and negative eigenvalues of Z_j.

**Comment by nikospetropo** [comment]
Yes I just saw that you define the creation operator with the minus sign;
what you have is indeed correct.
Sorry for the confusion.

Best,
Nikos Petropoulos
