### ISSUE TITLE
Broombridge schema for two-body integrals doesn't match spec?

### ISSUE THREAD

**Issue by christopherkang** [MicrosoftDocs/quantum-docs#13]
Under the [Two-Electron Integrals Object](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/chemistry/schema/spec_v_0_2?view=qsharp-preview#two-electron-integrals-object), the input is frequently said to come in the form ```[i, j, k, l]```, which is then used throughout formulas and symmetries.

However, this disagrees with the schema outlined in the [spec sheet](https://arxiv.org/pdf/1904.01131.pdf) (see page 20, listing 9, code line 21), which says that the format should operate in ```[i, l, j, k]```. Am I misreading something here? (E.g., are we already using the Mulliken convention here)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6747132f-77dc-58cc-b521-8838f9eaef3b
* Version Independent ID: f9cb66f1-7677-f488-71cb-f9721d66067a
* Content: [Broombridge Schema Specification (ver 0.2) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/chemistry/schema/spec_v_0_2?view=qsharp-preview#symmetries)
* Content Source: [articles/user-guide/libraries/chemistry/schema/spec_v_0_2.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/libraries/chemistry/schema/spec_v_0_2.md)
* Product: **quantum**
* GitHub Login: @guanghaolow
* Microsoft Alias: **gulow@microsoft.com**

**Comment by SoniaLopezBravo** [comment]
It seems that we still need to add a couple of lines clarifying the use of Dirac/Mulliken indexing and the fact that the deserializer does the conversion between them. I will take care of that.
