### ISSUE TITLE
there seems to be no clear way to connect q sharp to a quantum computer(not a simulator) thus making it rather useless... please make it a bit easier to find out how to connect to actual quantum machines.

### ISSUE THREAD

**Issue by jordan69420** [MicrosoftDocs/quantum-docs#133]
[Enter feedback here]

there is no documentation for connecting q# to an actual quantum machine(not a sim)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6746541-d849-5d22-3bea-633cd5aba7f0
* Version Independent ID: e7559785-831b-2b64-1333-1e5c8f7bc53c
* Content: [Reporting Quantum Development Kit bugs - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/contributing-reporting-bugs)
* Content Source: [articles/contributing-reporting-bugs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/contributing-reporting-bugs.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by SoniaLopezBravo** [comment]
Hello @jordan69420, thanks for your comment.
You can learn how to run your Q# programs on actual hardware in [Azure Quantum documentation](https://docs.microsoft.com/en-us/azure/quantum/overview-azure-quantum). We offer a variety of targets and providers to do that. Hope you find that useful.
