### ISSUE TITLE
Need Q#/ QDK landing page

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs#134]
I get a lot of questions at events and on my [Twitch streams](twitch.tv/crazy4pi314) and from folks in the [Q# Community](qsharp.community) forums (recently switched to [Discord](discord.qsharp.community)) as to where people can get started with learning about Q#. Often there is only really the activation energy to get them to click a link, and then they need easy to digest content that communicates the value and differentiators of the language and platform (most folks ask : is it another qiskit? is it just C#?). 

Right now, I send them to the docs, which the first docs page they see is a giant wall of text (not to mention that  Q# is buried under Azure quantum by a few layers. Consider the first page folks see when the google [qiskit](https://qiskit.org/) or [cirq](https://quantumai.google/cirq) which are the main other tools folks might be familiar with. Other MSFT platforms have sites like this too: https://dotnet.microsoft.com/ .  I recently found by randomly clicking link trails [this page](https://azure.microsoft.com/en-us/resources/development-kit/quantum-computing/) which is pretty close to what I was looking for but it being buried in Azure Quantum has made SEO for it really bad. Like I wish that docs.microsoft.com/qsharp or /quantum went to that page. Azure Quantum is important, but the amazing other tools built to support it deserve to stand on their own.

These are good examples of what I think Q#/QDK could really benefit from in capturing those first interested users and help communicate the differentiators of the language and platform.

**Comment by geduardo** [comment]
Hi @crazy4pi314, thank you very much for your elaborated feedback. It's really helpful!

For getting started with Q#, our team created a series of short courses in MS Learn to precisely fill that topic. You might want to check them out and maybe consider point your audience there as a starting point for using Q# ([First module here ](https://docs.microsoft.com/en-us/learn/modules/qsharp-create-first-quantum-development-kit/).

That Azure page you pointed out is from the marketing team and is not directly under our control, but I do agree in which adding a redirect from "docs.microsoft.com/qsharp" and "docs.microsoft.com/quantum" to there (or maybe to the  "get started with the QDK" article in our docs) would be helpful. What do you think @KittyYeungQ?

Also, we're aware that the current structure of the TOC makes a difficult to navigate through the content and users cannot find the information easily. We are currently working on restructuring the TOC to try to mitigate that and will do more as we receive user feedback over what things work and which don't.  However, there was a huge merging of content with the unification of the Azure Quantum docs and the QDK docs in recent months and it will take a bit of time until we get a curated organization that works for everyone. 

I will work with our team to explore new ways to make Q# getting started tutorials more discoverable. Thanks again!

**Comment by crazy4pi314** [comment]
> For getting started with Q#, our team created a series of short courses in MS Learn to precisely fill that topic. You might want to check them out and maybe consider pointing your audience there as a starting point for using Q# (First module here ).

This isn't exactly what I was meaning. The Learn modules are great, but the user profile/use case that I was looking for is someone who has barely enough activation energy to click a link to learn more. They might be attending a talk or looking at a Twitter post and want to learn more, but may not necessarily want to complete a module. They need to be able to see and read about the value of the language and platform before they would be willing to take a module (which will require many to make a login). 

> ... adding a redirect from "docs.microsoft.com/qsharp" and "docs.microsoft.com/quantum" to there (or maybe to the "get started with the QDK" article in our docs) would be helpful.

I think the content on the getting started page is good, but it is not a good _landing page_.

> we're aware that the current structure of the TOC makes it difficult to navigate through the content and users cannot find the information easily

Yeah that merger was really hard for me as a user, as I don't use the service (costs money) and since the docs.microsoft.com search is not great, it was super hard to find things again especially while I am working on stream. There are a lot of users out there that want to use the QDK and Q# and not the service as the additional cost to do so is not accessible.

> I will work with our team to explore new ways to make Q# getting started tutorials more discoverable.

That would be great, but to be clear it is not the tutorials that I think are the key resource. People won't take or start a tutorial if they can't figure out what something is or why they should want to learn it in the first place. This content is totally in the docs in a lot of different places, but its collecting that + UI/UX design to help improve the conversion on those initial clicks.

**Comment by KittyYeungQ** [comment]
Thank you @crazy4pi314 This raises several issues that we've been trying to address: a landing page for Q# and QDK and explanation of their relationships and distinction from Azure Quantum. The MS Learn and docs are not the best landing pages. Please let us know if this page addresses some of it, does it satisfy the community first comers and feedback you may have: https://azure.microsoft.com/en-us/resources/development-kit/quantum-computing/

**Comment by KittyYeungQ** [comment]
Closing this per conversation with @crazy4pi314 Thank you! We are following up on the SEO of the Q# and QDK page.
