### ISSUE TITLE
Missing information for easy start

### ISSUE THREAD

**Issue by SebastianHerzog** [MicrosoftDocs/quantum-docs#135]
I would recommend adding a link somwhere to this Microsoft doc page:
https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/additional-libraries?tabs=tabid-python

Because it is not clear that you have to do additional steps to find the necessary Microsoft MachineLearning Library.

Also a data.json is needed to fully test this code that should be mentioned somewhere or a link to a downloadable file should exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d160838-cb4e-dbf6-3f33-7ce09139d4d0
* Version Independent ID: 156b5681-2125-0515-fa0c-18d7a85ee34e
* Content: [Basic classification with the Quantum Machine Learning library - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/machine-learning/basic-classification?tabs=tabid-python)
* Content Source: [articles/user-guide/libraries/machine-learning/basic-classification.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/machine-learning/basic-classification.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @geduardo
* Microsoft Alias: **v-edsanc**

**Comment by SoniaLopezBravo** [comment]
Hello @SebastianHerzog , thank you so much for your comments. You are right, I will update that part of the documentation with your feedback.
