### ISSUE TITLE
Quantum

### ISSUE THREAD

**Issue by ahmedbinrafiq** [MicrosoftDocs/quantum-docs#136]
[Quantum technology cannot be created in this way. There is completely wrong information here.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61f9eb7a-972a-7fdd-9503-138ba8a3a08a
* Version Independent ID: 1e1396e2-7ba0-b1c5-8cf1-3b7654bba86e
* Content: [Get started with the Quantum Development Kit (QDK) - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-get-started-qdk)
* Content Source: [articles/install-get-started-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-get-started-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hello @ahmedbinrafiq.
The Quantum Development Kit is a SDK for Q#, a programming language designed specifically for quantum applications than you can run in various environments.  When you compile and run the program, it creates an instance of the quantum simulator and passes the Q# code to it.  Isolating the Q# code in the simulator ensures that the algorithms follow the laws of quantum physics and can run correctly on quantum computers. 
You can run Q# programs on an actual quantum computer with Azure Quantum, but the quantum simulators provided with the QDK provide accurate and reliable results.

You can find more information about Q# and Azure Quantum in our [Documentation](https://docs.microsoft.com/en-us/azure/quantum/).
