### ISSUE TITLE
"All binary operators are right-associative, except for ^" is wrong

### ISSUE THREAD

**Issue by user202729** [MicrosoftDocs/quantum-docs#14]
The sentence "All binary operators are right-associative, except for ^" should be "All binary operators are left-associative, except for ^".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fceffe7-26c1-3280-b51a-9a1a3cce7dff
* Version Independent ID: 17a16034-ddb6-01d5-a83d-b4c0bc466878
* Content: [Type Expressions in Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/language/expressions)
* Content Source: [articles/user-guide/language/expressions.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/language/expressions.md)
* Product: **quantum**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec@microsoft.com**

**Comment by dime10** [comment]
@gillenhaalb @cgranade Is this still relevant? I couldn't find the quoted sentence in the source.

**Comment by SoniaLopezBravo** [comment]
>@gillenhaalb @cgranade Is this still relevant? I couldn't find the quoted sentence in the source.

Me neither. I think table in the next section [Precedence and Associativity](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/precedenceandassociativity) solves the left/right-associativity issue. .
