### ISSUE TITLE
Term code snippets

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#141]
The `Term` code snippets on this page have full-stops at the end which should be removed:

```py
  File "<ipython-input-8-2162bffb41c1>", line 1
    Term(c=2, indices=[1,2]).
                             ^
SyntaxError: invalid syntax
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c8e5d0f-38a1-3081-d5c5-d11e0effbbe0
* Version Independent ID: b031b5c6-dcf0-1b49-510a-c253fcb2452e
* Content: [Quantum optimization term - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-term)
* Content Source: [articles/optimization-term.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-term.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @frtibble
* Microsoft Alias: **frtibble**

**Comment by dime10** [comment]
True, punctuation should not be present in code boxes. Thanks for catching this @frtibble!
