### ISSUE TITLE
Expand/enhance the "Further reading" page

### ISSUE THREAD

**Issue by gillenhaalb** [MicrosoftDocs/quantum-docs#16]
Quoting @cgranade from [here](https://github.com/MicrosoftDocs/quantum-docs-pr/pull/692/files#r379580147):

We may want to instead broaden the list of books, courses, and articles away from being a list of arXiv papers, and promote the section more? https://github.com/ebraminio/awesome-qsharp and https://qsharp.community/ are both good places to start looking for broader resources. @tcNickolas, are there any you'd like to suggest here as well?

**Comment by geduardo** [comment]
Closed via #71.
