### ISSUE TITLE
Document the .csproj difference between test project and executable/library project

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#162]
When we describe creating a test project in "Creating a Test Project", we focus on the Q# side of the things, but the .csproj file generated for a test project differs from one used for a library or a console application quite a lot. The .csproj files used in the Quantum Katas, for example, use 5 extra NuGet packages in addition to `Microsoft.Quantum.Katas` specific to the Katas project itself.

This information could be very helpful for somebody who wants to convert a project of one type to another type. We covered the contents of the .csproj file for a console application at https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/programstructure/ in quite a lot of detail, so it makes a lot of sense to do the same for test projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2358bb53-a09a-eef3-2eaf-86e9c98921ea
* Version Independent ID: bc21b0e9-7f31-cf83-72a8-726ed0986f76
* Content: [Test and debug quantum programs - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/testing-debugging?tabs=tabid-vs2019)
* Content Source: [articles/user-guide/testing-debugging.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/testing-debugging.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @tcNickolas
* Microsoft Alias: **mamykhai**

**Comment by dime10** [comment]
Thank you for the suggestion, we'll take a look!
