### ISSUE TITLE
Using the resource Id as it appears in the portal and suggested in the quickstart leads to an error

### ISSUE THREAD

**Issue by danielstocker** [MicrosoftDocs/quantum-docs#164]
Hi there, 

The quickstart article asks to copy the resource ID and location for a workspace from the portal here: 
![image](https://user-images.githubusercontent.com/9444698/116889927-f7e67900-abe1-11eb-920b-6ff24152f1b5.png)

If I do this, I get the values "/subscriptions/SUB/resourceGroups/GRP/providers/Microsoft.Quantum/Workspaces/RES" and "West US". 

Adding them into my quickstart code, this error is yielded when trying to send the problem to the service. 
![image](https://user-images.githubusercontent.com/9444698/116890076-1c425580-abe2-11eb-8063-c87457490ec1.png)

If I instead go to the quick start page on the workspace and copy the code from there it works fine.
![image](https://user-images.githubusercontent.com/9444698/116890240-4267f580-abe2-11eb-959d-d74ac7941e06.png)

![image](https://user-images.githubusercontent.com/9444698/116890267-4a279a00-abe2-11eb-9d56-9371c284b285.png)

Change Request for the article: Update the workspace constructor to match what's on the portal. 
I'll file a separate work item to improve error messaging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ac6bc6-9a0c-b1ee-c0a8-f06eb294cd81
* Version Independent ID: 4a0f49dc-2a95-fffd-a1e3-0dd3eac838de
* Content: [Optimization quickstart for Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-microsoft-qio)
* Content Source: [articles/quickstart-microsoft-qio.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-microsoft-qio.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @anraman
* Microsoft Alias: **anraman**

**Comment by SoniaLopezBravo** [comment]
Hi @danielstocker ! I tried to reproduce your error but the programs works well for me. Location is written in lowercase without spaces, did you do that?  

In Azure Portal ,and also in the previous article [Install and use Python SDK for optimization](https://docs.microsoft.com/en-us/azure/quantum/optimization-install-sdk), code for setting Azure environment includes "subscription_ID" and "resource_group", but those features are equivalent to set "resource_ID".

**Comment by dime10** [comment]
It appears the error stems indeed from the location field, as in your first try you used `West US` and in the second `westus`. The Azure portal does indeed show the location in capitalized and spaced writing, so we should add a note to our quickstarts to inform the user about the spelling requirement (lowercase, no space).

**Comment by dime10** [comment]
Actually I had a look at the code of Python SDK for Azure Quantum and it appears to be able to handle both types of input for the location: human-readable ("West US") and internal ("westus"). Apologies for the mistake.

As regards to your suggestion, the `Workspace` constructor should be able to handle both types of workspace identifiers: one via the `resource_id`, and another via the `subscription_id, resource_group, name` parameters. 

Unfortunately, I was not able to reproduce your error. @danielstocker are you able to share the full code you are using as well as your SDK version (from `pip show azure-quantum`) ?

**Comment by danielstocker** [comment]
Hey @dime10 & @SoniaLopezBravo thanks for looking into this. 
I do not know what I changed, but this is working for me now. 

Here is the rest of the code (just the shipping sample)

`from typing import List
from azure.quantum.optimization import Problem, ProblemType, Term

def createProblemForContainerWeights(containerWeights: List[int]) -> List[Term]:

    terms: List[Term] = []

    # Expand the squared summation
    for i in range(len(containerWeights)):
        for j in range(len(containerWeights)):
            if i == j:
                # Skip the terms where i == j as they can be disregarded:
                # w_i∗w_j∗x_i∗x_j = w_i*w_j∗(x_i)^2 = w_i∗w_j
                # for x_i = x_j, x_i ∈ {1, -1}
                continue

            terms.append(
                Term(
                    c = containerWeights[i] * containerWeights[j],
                    indices = [i, j]
                )
            )

    return terms

# This array contains a list of the weights of the containers:
containerWeights = [1, 5, 9, 21, 35, 5, 3, 5, 10, 11]

# Create the Terms for this list of containers:
terms = createProblemForContainerWeights(containerWeights)

# Create the Problem to submit to the solver:
problem = Problem(name="Ship Loading Problem", problem_type=ProblemType.ising, terms=terms)

from azure.quantum.optimization import ParallelTempering

# Instantiate a solver instance to solve the problem
solver = ParallelTempering(workspace, timeout=100) # timeout in seconds

# Optimize the problem
result = solver.optimize(problem)

def printResultSummary(result):
    # Print a summary of the result
    shipAWeight = 0
    shipBWeight = 0
    for container in result['configuration']:
        containerAssignment = result['configuration'][container]
        containerWeight = containerWeights[int(container)]
        ship = ''
        if containerAssignment == 1:
            ship = 'A'
            shipAWeight += containerWeight
        else:
            ship = 'B'
            shipBWeight += containerWeight

        print(f'Container {container} with weight {containerWeight} was placed on Ship {ship}')

    print(f'\nTotal weights: \n\tShip A: {shipAWeight} tonnes \n\tShip B: {shipBWeight} tonnes')

printResultSummary(result)`

Previously if I put

`from azure.quantum import Workspace

# Copy the settings for your workspace below
workspace = Workspace(
    resource_id = "RESOURCE ID AS COPIED FROM THE PORTAL", # add the Resource ID of the Azure Quantum workspace you created
    location = "West US"     # location as copied from the portal
)
workspace.login()`

in front, I got the error. The error did not occur for 'westus'

I have not upgraded the Python SDK or changed anything else in my setup.
This is really weird. 

The version I used all along was 

`Name: azure-quantum
Version: 0.16.2104.138035
Summary: Python client for Azure Quantum
Home-page: https://github.com/microsoft/qdk-python
Author: Microsoft
Author-email: None
License: UNKNOWN
Location: c:\users\dasto\appdata\roaming\python\python39\site-packages
Requires: msrestazure, msal, numpy, azure-devtools, azure-storage-blob
Required-by:`

Anyway sorry to bother you and thanks for spending the time.
