### ISSUE TITLE
1QBit Path-Relinking Solver

### ISSUE THREAD

**Issue by maximilianluc** [MicrosoftDocs/quantum-docs#168]
[Enter feedback here]
Hi! The path-relinking solver description is the same as the pticm solver description. 
Thanks, Max
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1e82e1-99de-c3a3-1e18-f4e98ffd287e
* Version Independent ID: d8635fa9-bb30-12eb-aef3-8b58c81b3080
* Content: [List of optimization targets on Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/qio-target-list)
* Content Source: [articles/qio-target-list.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/qio-target-list.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @geduardo
* Microsoft Alias: **kitty**

**Comment by dime10** [comment]
Hi @maximilianluc, thanks a lot for pointing this out! I will take care of this issue.
