### ISSUE TITLE
Name of the article in the table of contents and on the page do not match

### ISSUE THREAD

**Issue by danielstocker** [MicrosoftDocs/quantum-docs#172]
The article name is "Which optimization solver should **I** use?"
The name in the TOC is "Which solver should **you** use?"

Not sure if that's a 'won't fix' but I personally prefer consistency so wanted to raise it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa394b2-60ff-0f87-3c38-fa9406b9b3c0
* Version Independent ID: 84333d4f-1c6d-7af0-7394-d741353d6b23
* Content: [Which optimization solver should I use? - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-which-solver-should-you-use)
* Content Source: [articles/optimization-which-solver-should-you-use.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-which-solver-should-you-use.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @quantumrandom
* Microsoft Alias: **dasteige**

**Comment by dime10** [comment]
Thank you for pointing this out, I will take a look at the style guide to update this.
