### ISSUE TITLE
Document throwOnReleasingQubitsNotInZeroState parameter in full state simulator docs

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#181]
The page documents other constructor parameters, but not this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c36e49-20c7-4713-d3d7-7faa5e3f0c7e
* Version Independent ID: 2b067d7a-9b68-8dfd-624b-dad1d8df5588
* Content: [Full state quantum simulator - Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/machines/full-state-simulator)
* Content Source: [articles/user-guide/machines/full-state-simulator.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/machines/full-state-simulator.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @anpaz
* Microsoft Alias: **anpaz**

**Comment by dime10** [comment]
Thanks @tcNickolas for pointing this out. I will document the other two parameters.
