### ISSUE TITLE
Document time units for Average Queue Time

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#182]
It's not clear from the documentation what is the time unit for Average Queue Time (both for IonQ and for Honeywell pages). I'm getting values between a hundred and 1.5k, so it looks like seconds are the most likely time unit, but if we're suggesting the reader to use this information to estimate their wait time, it's a good idea to clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7bff88d-7bc4-e264-827e-6a97f37c9fc4
* Version Independent ID: 0709db49-95c6-c7ae-b62f-60862420f018
* Content: [IonQ quickstart for Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-ionq)
* Content Source: [articles/quickstart-ionq.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-ionq.md)
* Service: **azure-quantum**
* Sub-service: **computing**
* GitHub Login: @mblouin
* Microsoft Alias: **mblouin**

**Comment by dime10** [comment]
Good point, I will look into this!
