### ISSUE TITLE
Document libraries layout in contribution guide.

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs#19]
As we complete MicrosoftDocs/quantum-docs-pr#355, we should ensure that we document somewhere the way that we use files, folders, and namespaces, so that contributors can more easily fit their work into our existing structures.

**Comment by dime10** [comment]
Hi @cgranade, I'm looking at your suggestion. Would you be able to expand a bit on what exactly you had in mind?

I'm assuming you want to document this repository: https://github.com/microsoft/QuantumLibraries 
Would the layout not be better documented in the repository readmes where the reader can immediately see and interact with the file/folder structure?
I guess information on namespaces would indeed be better located in the contribution guide. If so, what do you think of adding a page to the [contribution guide](https://docs.microsoft.com/en-us/azure/quantum/contributing-overview) titled 'Contributing to Libraries'?

**Comment by dime10** [comment]
Thank you very much for your comments, these will be helpful in updating the contribution guide!

Closing this issue as this item has been entered into the backlog.
