### ISSUE TITLE
Document passing parameters and getting outputs from Q#

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#190]
Sections "Q# with host programs" and "Q# Jupyter Notebooks" have sections on passing parameters, but they only describe very simple scenarios such as passing an integer. Some of the things a person who's trying to do something more interesting will struggle with are:

* Passing arrays - `QArray` is not documented, and only occurs in API documentation.
* Passing callables as arguments.
* Passing qubits as arguments from classical code (not possible, but needs documentation on this).
* Receiving results from operations, the nuances of tuples and arrays in the results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206e9bfe-7e73-7f7d-5243-95978ec0d613
* Version Independent ID: fea0833b-00dd-d61a-f197-115050e1b65f
* Content: [Ways to run a Q# program - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/host-programs?tabs=tabid-python)
* Content Source: [articles/user-guide/host-programs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/host-programs.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec**

**Comment by SoniaLopezBravo** [comment]
Thank you for the feedback! So this a a follow-up to #163, we need to expand and improve our documentation on passing parameters. We'll take care of that.

**Comment by SoniaLopezBravo** [comment]
Closing this issue as I created a work item for it, you can see it in [#1856729](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1856729)

**Comment by tcNickolas** [comment]
In the open source world the issues are typically closed when they are resolved or when they are deemed not worthy of a fix. I recommend leaving the issues that will be worked upon open until they are fixed, regardless of whether a mirror work item in an internal system is created, so that users who don't have access to the internal system can see the status of the issue.

**Comment by cgranade** [comment]
Strongly seconded. Best practice on other QDK repos is to close issues only when there is a concrete resolution, and to use a label like `Resolution-Done` or `Resolution-Invalid` to communicate that resolution to users.
