### ISSUE TITLE
OnlineProblem sample links to the same page and there doesn't seem to be a sample on the page

### ISSUE THREAD

**Issue by danielstocker** [MicrosoftDocs/quantum-docs#192]
https://docs.microsoft.com/en-us/azure/quantum/optimization-problem#onlineproblem

Has a link "here" that seems to link to a usage sample for the OnlineProblem class. When clicking the link, it takes me to the optimization-problem site, but there isn't a usage sample there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1172b3-683a-12e0-15cf-70fce1ec0ccb
* Version Independent ID: 38eac5c4-2819-21b5-b03a-985f1a0b2901
* Content: [Quantum optimization problem - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-problem)
* Content Source: [articles/optimization-problem.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-problem.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @george-moussa
* Microsoft Alias: **georgenm**

**Comment by dime10** [comment]
Indeed, seems to be a typo in the cross-reference. Thank you for catching this!
