### ISSUE TITLE
The term "ancilla" should be removed in favor of "auxiliary" 

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs#214]
The term "ancilla" is problematic, and should be replaced by "auxiliary." We've done so in other parts of the documentation, but it looks like this page may have been missed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d86f1e-9754-01fb-3521-1edc2b72d532
* Version Independent ID: 59733c91-9491-544f-6aba-e3049bcd464d
* Content: [Quantum characterization and statistics - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/characterization)
* Content Source: [articles/user-guide/libraries/standard/characterization.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/standard/characterization.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @Bradben
* Microsoft Alias: **martinro**

**Comment by Bradben** [comment]
assigned to[ work item 381](https://dev.azure.com/Qtechwriters/Q%20tech%20writing/_queries/edit/381/?triage=true)
