### ISSUE TITLE
⚠️ IMPORTANT: Where to submit feedback or ask for support.

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs#22]
For issues related to the documentation use this repository. 
For technical issues with Azure Quantum and optimization please use [Azure Support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest) or [Azure Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-quantum.html).
For feature asks around Azure Quantum please use the [feedback forum](https://feedback.azure.com/forums/932905-azure-quantum).
Q# and QDK continue to be supported via their GitHub repos.

**Comment by SoniaLopezBravo** [comment]
Closing as this is included as a template when creating new GitHub issues.
