### ISSUE TITLE
Get the below message while created Azure Quantum on any provider

### ISSUE THREAD

**Issue by shreyas-19** [MicrosoftDocs/quantum-docs#23]
invalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Quantum' for api version

**Comment by geduardo** [comment]
Hi @shreyas-19, thank you for filling this issue. Unfortunately, this repository is only for issues related to the documentation. To make sure you get the best level of support, it would be great if you could
report your issue via [https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest] or Azure Q&A(https://docs.microsoft.com/en-us/answers/topics/azure-quantum.html) if you don't have access to an [Azure support plan](https://azure.microsoft.com/en-us/support/plans/)
