### ISSUE TITLE
How to create applications for AQ: Generalize IonQ step-by-step guide to all target types

### ISSUE THREAD

**Issue by dime10** [MicrosoftDocs/quantum-docs#241]
"[This page] has a step by step guide for submitting jobs to IonQ, but we don't have such a section for Honeywell. That said, the instructions are all the same save for the strings used for execution target. Maybe that section could be moved below the descriptions of both profiles and generalized to explain submission to any target by name?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c37b779-f962-8cf4-302d-a48e886eeaff
* Version Independent ID: 69bcd816-20ee-3191-fa6d-21da3c2a3bdb
* Content: [Create and run Q# applications in Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/how-to-create-applications-for-azure-quantum)
* Content Source: [articles/how-to-create-applications-for-azure-quantum.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-create-applications-for-azure-quantum.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by KittyYeungQ** [comment]
Sounds good
