### ISSUE TITLE
Add code samples for cancelling a job

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#248]
We have code samples for get_job and list_job, but not for cancel_job, which we should add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa34395-1c02-a784-313b-88821893b9cc
* Version Independent ID: 4b2ffdd9-4943-ca31-d038-d1a22087a648
* Content: [Manage optimization jobs - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-job-management)
* Content Source: [articles/optimization-job-management.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-job-management.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by frtibble** [comment]
This shows how to cancel a `Job` using its `id`. The `id` of a `Job` can be found using the `list_jobs` method, or by viewing the information in the Job Management tab of your Azure Quantum workspace in the Azure portal:

```py
job = workspace.get_job('5d2f9cd70f55f149e3ed3aef')
workspace.cancel_job(job)

print(job.details.status)
> Cancelled
```

**Comment by dime10** [comment]
Good point, thanks for suggesting this @frtibble.
