### ISSUE TITLE
quantum

### ISSUE THREAD

**Issue by studioonze** [MicrosoftDocs/quantum-docs#266]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61f9eb7a-972a-7fdd-9503-138ba8a3a08a
* Version Independent ID: 1e1396e2-7ba0-b1c5-8cf1-3b7654bba86e
* Content: [Get started with the Quantum Development Kit (QDK) - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-get-started-qdk)
* Content Source: [articles/install-get-started-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-get-started-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hi @studioonze, could you be more specific? What is the issue you are referring to? We will try to help you solve it.
