### ISSUE TITLE
New syntax update causing problems with sample code snippets

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs#28]
Due to recent changes in the code files of the Samples in the [samples repository](https://github.com/microsoft/Quantum), some code snippets that were being pulled from the original sample files by using hard-coded line specifications now are wrong since they are pulling incorrect lines.

Example in issue #4. 

A direct fix would be to change the lines in the Markdown files to match the new ones, but I fear that this will happen again in the future with further updates of the samples code. Maybe we should embed directly the code in the text rather than using an include file. It's not a perfect solution, but at least it keeps the docs correct, although samples tutorials might be out of sync with the latest updates.

Tagging @KittyYeungQ, @cgranade, @Bradben @dime10 @SoniaLopezBravo for discussion.

**Comment by SoniaLopezBravo** [comment]
But if samples are ok, do we know why hard-coded line specifications are pulling incorrect lines? @geduardo 

In some articles we embed directly the code, maybe we should do that for all documentation and in the future keep an eye on both samples tutorials and the code in the text so we keep them updated. 

Also, regarding issue #4 , the screenshot below the code is outdated, it still depicts `using` instead of `use`. This probably happens in others files. We have to update screenshots too.

**Comment by geduardo** [comment]
@SoniaLopezBravo the includes are pulling incorrect lines because the samples were modified and thus, some lines changed places. So previous tags specifying the lines are now incorrect.

**Comment by dime10** [comment]
So to me it seems we have two options, neither of which necessary prevent the need for manual updates to the docs when the samples change. If there are other options it would be great to consider those as well.
 
- **include from sample**: This keeps the text content in the markdown separate from other elements. It also automatically incorporates changes to the source as long as line numbers don't change. However, it's more prone to breaking the instructions when line numbers do change.
- **embedded markdown**: This seems safer as the doc will remain self-consistent, albeit possibly outdated. Requires manual updates every time the samples change to stay in sync.

I think either way if changes to the code happen we'll want to take a look to make sure the instructions we give in the documentation still work, so embedding might be a good idea in this instance.

**Comment by geduardo** [comment]
Yes, you are right @dime10, but from a user-experience point of view, I think it's better to find outdated things (that usually have some relaxed deprecation time) than things that are wrong because some lines are missing...

**Comment by dime10** [comment]
> Yes, you are right @dime10, but from a user-experience point of view, I think it's better to find outdated things (that usually have some relaxed deprecation time) than things that are wrong because some lines are missing...

Yes I agree.

**Comment by SoniaLopezBravo** [comment]
Unless we find a better solution, I think we should go for manual updates in the text. Things might be outdated for a while but at least they won't be wrong, and users can always check [Release Notes](https://docs.microsoft.com/en-us/azure/quantum/qdk-relnotes) and see the latest updates.
