### ISSUE TITLE
"Standard libraries" page mentions outdated package

### ISSUE THREAD

**Issue by samarsha** [MicrosoftDocs/quantum-docs#281]
The "Standard libraries" page says:

> The Microsoft.Quantum.Development.Kit NuGet package installed during installation and validation provides the Q# compiler, and parts of the standard library that are implemented by the target machines. The Microsoft.Quantum.Standard package provides the portion of the Q# standard libraries that are portable across target machines.

However, the Microsoft.Quantum.Development.Kit package has been deprecated for a long time (replaced by Microsoft.Quantum.Sdk) and has recently been removed.

I'd like to update this paragraph, but I'm not sure what the intent of this page is. Is it intended to provide a breakdown of all the different standard library packages? There are several of those, like Microsoft.Quantum.QSharp.Core, Microsoft.Quantum.QSharp.Foundation, Microsoft.Quantum.Standard, as well as the target-specific decompositions like Microsoft.Quantum.Type{1,2,3}.Core.

But the Microsoft.Quantum.Sdk package should automatically handle dependencies for the needed standard library packages. Is it enough to just mention that Microsoft.Quantum.Sdk automatically includes the standard library without describing all of the package details?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 444f8056-d62d-c359-8c63-cd35798e94ff
* Version Independent ID: 0f3bb81a-fc74-7f11-3a53-a0a7770eb341
* Content: [Introduction to Microsoft Q# standard libraries - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/)
* Content Source: [articles/user-guide/libraries/standard/index.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/standard/index.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro**

**Comment by dphansen** [comment]
Work item created in Azure DevOps for the content team's backlog: [#1857980](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1857980)
