### ISSUE TITLE
Add information about Job.details

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#285]
Users can get full details about the job submission, however we haven't documented this (e.g. in https://docs.microsoft.com/en-us/azure/quantum/optimization-job-reference or https://docs.microsoft.com/en-us/azure/quantum/optimization-job-management):

```
job = workspace.get_job(jobId)
print(job.details)
```

We could add a table for the fields returned, and a description of each:

```
{
    "additional_properties": json object, e.g. if the job is being cancelled,
    "id": string, the job id,
    "name": string, the name of the job,
    "container_uri": string, where the job data is stored,
    "input_data_uri": string, where the input data is stored,
    "input_data_format": string, e.g. "microsoft.qio.v2"
    "input_params": json object, includes solver specific parameter information, such as beta values, or population size,
    "provider_id": string, e.g. "microsoft",
    "target": string, the name of the target for instance e.g."microsoft.substochasticmontecarlo.cpu",
    "metadata":  e.g. None,
    "output_data_uri":  string, where the output data is stored,
    "output_data_format": string, e.g. "microsoft.qio-results.v2",
    "status": string, status of the Job e.g. "Succeeded",
    "creation_time": datetime, when the job was created,
    "begin_execution_time": datetime, when the job began execution,
    "end_execution_time": datetime, when the job completed,
    "cancellation_time":  e.g. None, when the job was cancelled (if applicable),
    "error_data": e.g None, any error details during job submission
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe08ab8-fc39-0b00-090a-ffe0b9ee1aa7
* Version Independent ID: d937bd15-aa63-d350-be2d-00b412796e47
* Content: [Quantum optimization job - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-job-reference)
* Content Source: [articles/optimization-job-reference.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-job-reference.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @george-moussa
* Microsoft Alias: **georgenm**

**Comment by SoniaLopezBravo** [comment]
Work item created in Azure DevOps: [1859169](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1859169)
