### ISSUE TITLE
'term' should be written with uppercase 'T', i.e. 'Term' - otherwise code fails to execute

### ISSUE THREAD

**Issue by hsirtl** [MicrosoftDocs/quantum-docs#29]
Submitting this code in a Jupyter notebook gives me following error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-91b0b25c5dcc> in <module>
      1 terms = [
----> 2     term(c=-9, indices=[0]),
      3     term(c=-3, indices=[1,0]),
      4     term(c=5, indices=[2,0]),
      5     term(c=9, indices=[2,1]),

NameError: name 'term' is not defined

'term' should be written with uppercase 'T', i.e. 'Term'

Following code works fine

terms = [
    Term(c=-9, indices=[0]),
    Term(c=-3, indices=[1,0]),
    Term(c=5, indices=[2,0]),
    Term(c=9, indices=[2,1]),
    Term(c=2, indices=[3,0]),
    Term(c=-4, indices=[3,1]),
    Term(c=4, indices=[3,2])
]

problem.add_terms(terms=terms)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888d2bd3-ae45-2d93-6bc3-9e9a16010c1a
* Version Independent ID: 5c739c1d-d6f0-2247-1eba-f38fa2ee6a11
* Content: [Install and use the Python SDK for optimization - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-install-sdk)
* Content Source: [articles/optimization-install-sdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-install-sdk.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @anraman
* Microsoft Alias: **anraman**

**Comment by anraman** [comment]
Created PR to address this: https://github.com/MicrosoftDocs/quantum-docs/pull/30

**Comment by anraman** [comment]
Good catch @hsirtl! Thanks for raising :)
