### ISSUE TITLE
Terseness makes this equation wrong, Kindly see image 

### ISSUE THREAD

**Issue by shibasis0801** [MicrosoftDocs/quantum-docs#3]
![image](https://user-images.githubusercontent.com/13601918/106877076-6066ac80-66fe-11eb-941c-c8ca63338c89.png)

Hadamard multiplication > 
This equation is wrong after the matrix multiplication. 
Yes they have equal probability and obviously the author knows this stuff. 
But equating a matrix directly to the probabilty of collapsing is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63efee25-7d4e-9822-2459-e8e0d57829ba
* Version Independent ID: b61f5114-eeca-8c8f-78d5-841928aaa06a
* Content: [Linear algebra for quantum computing - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/overview-algebra-for-quantum-computing)
* Content Source: [articles/overview-algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/overview-algebra-for-quantum-computing.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hi @shibasis0801 ,
Thank you for your feedback on our Azure Quantum Documentation page. You are right, the way this equation is formulated is not correct. Matrix multiplication cannot be equal to probability and, without further information, it might be confusing for the reader. 

We will rewrite that part and it will be updated soon. We appreciate your comments.
