### ISSUE TITLE
Relocate page for working with Azure CLI?

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#304]
This page appears in Optimization > How-to guides, would it make more sense in the Quantum Computing > How-to guides section? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05945c3a-0ba7-4ea6-9b7c-07cd96a5051a
* Version Independent ID: 3a010540-d36e-6334-06ad-668842e2052f
* Content: [Manage quantum workspaces with the Azure CLI - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/how-to-manage-quantum-workspaces-with-the-azure-cli)
* Content Source: [articles/how-to-manage-quantum-workspaces-with-the-azure-cli.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-manage-quantum-workspaces-with-the-azure-cli.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @ricardo-espinoza
* Microsoft Alias: **ricardoe**

**Comment by SoniaLopezBravo** [comment]
Hi @frtibble. Thanks for pointing this out. In fact, this section should be in both "How-to-guides", such as other shared sections like "Work with jobs" and "Submit jobs". I will fix that.

**Comment by SoniaLopezBravo** [comment]
Work item created in DevOps, [#1862830](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1862830)

**Comment by SoniaLopezBravo** [comment]
I am closing this issue as this PR https://github.com/MicrosoftDocs/quantum-docs-private/pull/433 fixes it.
