### ISSUE TITLE
Azure Quantum CLI command produces an error

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#31]
The documentation has the command for showing the result of a job:
```
az quantum job show -j yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy -o table
```

when I run this I get the following:
```
the following arguments are required: --job-id/-id
```

Do the docs need updating?

This works fine:
```
az quantum job show --job-id yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy -o table
```

I'm using version 2.19.1 of the Azure CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d79774e-f926-afee-b95f-82c228e7989a
* Version Independent ID: 2da4df7d-f6e1-744b-3c45-c344af90ff29
* Content: [Submit jobs to Azure Quantum with the Command Line Interface - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs-with-azure-cli)
* Content Source: [articles/how-to-submit-jobs-with-azure-cli.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-submit-jobs-with-azure-cli.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by geduardo** [comment]
Those arguments were changed in one of the last versions (https://github.com/MicrosoftDocs/quantum-docs-private/pull/174), previously they were different. Have you tried updating the quantum extension for the Az CLI?

**Comment by frtibble** [comment]
I had checked for updates, but I've just uninstalled and re-installed now and it's working. Thanks!
