### ISSUE TITLE
"Submit Optimization Jobs" in Optimization -> How-to-Guides talks about quantum computing instead of optimization

### ISSUE THREAD

**Issue by ashwinmayya** [MicrosoftDocs/quantum-docs#315]
This section is supposed to talk about optimization jobs, but instead it talks about quantum computing jobs.
https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs?tabs=tabid-python

**Comment by SoniaLopezBravo** [comment]
@ashwinmayya Thank you for your feedback! We are aware of that, we are currently working on two separates "How to submit jobs" articles for quantum computing and optimization.

**Comment by SoniaLopezBravo** [comment]
Work item in DevOps: [#1865777](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1865777)
