### ISSUE TITLE
Job management page

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#316]
Small request - could we add sub headers to this page, e.g. "List jobs", "Get jobs", "Cancel a job" to allow for easier linking to specific sections? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa34395-1c02-a784-313b-88821893b9cc
* Version Independent ID: 4b2ffdd9-4943-ca31-d038-d1a22087a648
* Content: [Manage optimization jobs - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-job-management)
* Content Source: [articles/optimization-job-management.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-job-management.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by SoniaLopezBravo** [comment]
@frtibble Sure! I have created a work item in DevOps [#1867426](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1867426)

**Comment by frtibble** [comment]
Thanks Sonia!
