### ISSUE TITLE
Sentence Structure is too Complex - Unclear Meaning

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/quantum-docs#318]
This paragraph under "What is a quantum program"
_An important consequence of that is that Q# has no ability to introspect into the state of a qubit or other properties of quantum mechanics directly, which guarantees that a Q# program can be physically executed on a quantum computer. Instead, a program can call operations such as Measure to extract classical information from a qubit._
The first sentence seems to say that a Q# program can be run on quantum computer. The next sentence begins with the word "Instead" negating what was implied in the prior sentence.
This is confusing, what does this collections of words really mean?

As a person who tends to write long complex sentences, the overuse of the comma along with the switching of thoughts in the same sentence all to often employed; seen many times in articles, documentation, and writing in other areas is a common practice.

I have read the opening paragraph and this paragraph several times to try and flesh out what Q# does. Knowing about Quantum states and all this is great, A less confusing set of opening paragraphs would be helpful. The old "Tell me what you are about to tell me. Tell me. Then tell me what you told me." I also know that there is a page that is the conceptual overview of Q# in the documentation. I read it.

In this case we are talking about Q# (title of the page).
The first sentence in the first paragraph "implies" that there is some "other" program in the quantum computer.
The next sentence seems to say that Q# is like an observer/controller of the quantum program. 
The last sentence in first paragraph is fluff.

The next paragraph (the one in question here) stating that there are limitations of some sort.
The first sentence has two main thoughts with the second thought being unclear. Does it mean that a Q# program runs on ANY quantum computer or does it means something else? Does limiting Q# give us some benefit?

What is the main purpose of Q# in the context of this page?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1310be9-5ecf-80aa-ef1c-b04c1159260a
* Version Independent ID: 3d2af32f-4b6a-9757-0598-df62b503c099
* Content: [Q# programming language introduction - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/programs)
* Content Source: [articles/user-guide/programs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/programs.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @beheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
Hi @laultman, thank you for your elaborate and detailed comment. We really appreciate this kind of feedback. 
It is true that from that paragraph it can be hard to understand the advantages of Q# and how it is implemented on a quantum computer.  I will take care of that and work on the exhibition of these ideas.
