### ISSUE TITLE
Neat use of the bang  unpack operator

### ISSUE THREAD

**Issue by TonyHoldroyd** [MicrosoftDocs/quantum-docs#323]
Not an issue as such, but an observation, that the examples that show  the use of the bang unpack operator might usefully include an example to show how it can be used to unpack a newtype operation parameter in a neater way than with individual item extraction using ::
For example:
newtype  TwoBitString = (bit1: String, bit2: String);
........
operation Str(bits: TwoBitString):String {
            //let b1= bits::bit1;
            //let b2 = bits::bit2;
            let (b1, b2) = bits!;
            return b1+b2;
    }
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b76f2d-ea42-8fb5-d2bf-f40de79cac37
* Version Independent ID: e25b13ab-1ac2-c8dd-927d-3384f8de1211
* Content: [Item access in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/itemaccessexpressions#item-access-for-user-defined-types)
* Content Source: [articles/user-guide/language/Expressions/itemaccessexpressions.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Expressions/itemaccessexpressions.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
@TonyHoldroyd thank you so much for your feedback. These contributions help us to grow and improve. I will include this example in the documentation.

**Comment by SoniaLopezBravo** [comment]
Work item created, [#1871521](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1871521)

**Comment by TonyHoldroyd** [comment]
Thank you very much Sonia, I was pleased to ascertain  that the syntax supported that usage, and even more pleased to make my little contribution to the docs.

**Comment by TonyHoldroyd** [comment]
Hello Sonia,
I don't know if it's worthy of inclusion, but this also works and is even neater:

newtype  TwoBitString2 = (bits: String[]);
operation Str2(bits: TwoBitString2):String {
            return bits![0] + bits![1];
}

Best,
Tony
