### ISSUE TITLE
IonQ quickstart formatting issue

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#33]
There's a formatting issue here and in the Honeywell quickstart:
![image](https://user-images.githubusercontent.com/32080479/107779239-fb820680-6d3c-11eb-8144-f45fe071af65.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7bff88d-7bc4-e264-827e-6a97f37c9fc4
* Version Independent ID: 0709db49-95c6-c7ae-b62f-60862420f018
* Content: [IonQ quickstart for Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-ionq)
* Content Source: [articles/quickstart-ionq.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-ionq.md)
* Service: **azure-quantum**
* Sub-service: **computing**
* GitHub Login: @mblouin
* Microsoft Alias: **mblouin**

**Comment by geduardo** [comment]
Thanks for noticing, I created a PR to fix it.
