### ISSUE TITLE
command prompt

### ISSUE THREAD

**Issue by marco402** [MicrosoftDocs/quantum-docs#332]
Just to run from visual studio, in project properties tab debugger
      put --count 1000 --initial One or --count 1000 --initial Zero in application arguments.
 else
      menu tools -->command prompt

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93695b8-e683-f357-7a64-6a9420641aae
* Version Independent ID: e2ac33fb-fb98-45b0-cd6c-23b3e57c0fb8
* Content: [Explore entanglement with Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/tutorial-qdk-explore-entanglement)
* Content Source: [articles/tutorial-qdk-explore-entanglement.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/tutorial-qdk-explore-entanglement.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hi @marco402. Could you be more specific? What is the issue or comment of yours about this page?

**Comment by marco402** [comment]
Hi Sonia
My message was just to clarify the documentation on the page to launch the program:

by the method specified by specifying menu tools -->command prompt

or by the arguments in project properties->tab debugger zone application arguments
                      --count 1000 --initial One or --count 1000 --initial Zero

Marc

**Comment by SoniaLopezBravo** [comment]
@marco402 The thing is you can run this program using any IDE of your preference (Visual Studio, Visual Studio Code, Jupyter Notebook, etc) and .NET CLI language, and each environment has different features when it comes to running the code. 
This is why the documentation only tells that you need to specify `count` and `initial` arguments from the command prompt, but no further details as those will depend on the chosen environment.
