### ISSUE TITLE
for loop syntax

### ISSUE THREAD

**Issue by TonyHoldroyd** [MicrosoftDocs/quantum-docs#340]
[Enter feedback here]

I think it would be really worth having a more straightforward  example that shows you can use a for.. in.. {} directly like this:

for (a, b) in [(x, y]  {
.....
}
---
This would also show up if there were a formal presentation of the syntax rather than a textual description.
It would also be really useful if this syntax were on the appropriate place on the Q# Quick Reference sheet.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecab8e9-eef4-bde4-ff6e-5310cf54bbd0
* Version Independent ID: 28e2aa5b-2be7-cd2c-7e79-9e4cd8c45b98
* Content: [Iterations and loops in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/statements/iterations)
* Content Source: [articles/user-guide/language/Statements/iterations.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Statements/iterations.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
Hi @TonyHoldroyd ! Thank you so much for your feedback.

Actually, there is something like the example you are suggesting in the code snippet:
```
for (index, measured) in results {
......
}
```
where `results += [(index, M(qubits[index]))]`. 
Adding more examples might be confusing, and also code snippets try to offer practical examples of the use of quantum physics and Q#.
