### ISSUE TITLE
PDF of this doc?

### ISSUE THREAD

**Issue by TonyHoldroyd** [MicrosoftDocs/quantum-docs#341]
[Enter feedback here]
Would it be possible, please, to provide this document as a printable PDF, like the Q# Quick Reference Guide.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9fcca6-76bd-468b-c388-952832e4b5e3
* Version Independent ID: dd1ca9b0-6388-bf2e-ad0d-75e80d30390a
* Content: [Q# Style Guide - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/contributing-style-guide?tabs=guidance)
* Content Source: [articles/contributing-style-guide.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/contributing-style-guide.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by SoniaLopezBravo** [comment]
Hi @TonyHoldroyd !
Which _Q# Quick Reference Guide_ do you mean? I don't think it would be possible, the documentation is constantly improving and updating, so a PDF could become obsolete.

**Comment by TonyHoldroyd** [comment]
Ciao Sonia,
This is the one:
https://github.com/microsoft/QuantumKatas/blob/main/quickref/qsharp-quick-reference.pdf
Surely a PDF of a style guide would not become obsolete except in the very long term. it would be very handy to have a paper copy of the style guide to hand whilst coding.

**Comment by SoniaLopezBravo** [comment]
I think maybe @tcNickolas can answer your question, she has created most of the Quantum Katas content. Mariia, what do you think about Tony's suggestion?

**Comment by cgranade** [comment]
@SoniaLopezBravo @TonyHoldroyd: I wrote and maintain the Q# style guide, happy to help here. At the moment, we don't have a quick reference version of the style guide available as a PDF, but the style guide content is included in the [PDF automatically generated from the full docs](https://docs.microsoft.com/en-us/azure/quantum/opbuildpdf/toc.pdf?branch=live), currently starting at page 529.

**Comment by TonyHoldroyd** [comment]
Thank you Sonia, thank you Chris, it''s really handy to know about the pdf - there are other very useful sections I'll be printing out as well as the important style guide. I'm more than a bit old (fashioned) and for some things you just can't beat seeing them on paper.
