### ISSUE TITLE
Incorrect rendering of operators that include |

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#352]
In the precedence table, conditional operator `? |` and bitwise OR `|||` are rendered with the escape symbols, `? \|` and `\|\|\|`, respectively. The [matching page in qsharp-language repo](https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/3_Expressions/PrecedenceAndAssociativity.md) renders them fine, so it looks like GitHub and documentation use different escaping processes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81868634-70de-0d44-8b6a-9048b918e532
* Version Independent ID: b9044d2e-c022-e51b-99f0-4d314b98428e
* Content: [Operator precedence in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/precedenceandassociativity#operators)
* Content Source: [articles/user-guide/language/Expressions/precedenceandassociativity.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Expressions/precedenceandassociativity.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
@Bradben, do you know where I can search for the rendering in docs to solve this? Thanks!

**Comment by Bradben** [comment]
That's a new one - apparently Docs doesn't support escaped pipes within a markdown table, and this page is the only one in the docset that tries to use it.

I did find [this article](https://www.designcise.com/web/tutorial/how-to-escape-the-pipe-character-in-a-markdown-table) with a html workaround, though. It works in the VS Code preview, but I haven't tested it in a full GitHub preview build yet. 

| Col 1| Col 2 |
| -- | -- |
| <code>?&vert;</code> | <code>&vert;&vert;&vert;</code> |

**Comment by SoniaLopezBravo** [comment]
Work item created in DevOps [#1883984](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1883984)

**Comment by SoniaLopezBravo** [comment]
Closing this issue as it was solved in https://github.com/microsoft/qsharp-language/pull/115
