### ISSUE TITLE
PDF generation does not respect Mathjax math mode

### ISSUE THREAD

**Issue by filipw** [MicrosoftDocs/quantum-docs#354]
When browsing the documentation pages, it is possible to generate PDF out of the entire documentation site using the "download PDF" link in the bottom left corner ([direct link](https://docs.microsoft.com/en-us/azure/quantum/opbuildpdf/toc.pdf?branch=live)).

This works well for all the content and code, and exports the entire site into a single large PDF, which is a great idea. 
However, the math mode (which is using Mathjax) is not respected, which leads to the unprocessed output for all math sections e.g.:

<img width="1172" alt="Bildschirmfoto 2021-09-27 um 20 36 02" src="https://user-images.githubusercontent.com/1710369/134966007-74de5454-d4ca-43e8-a785-4f255792f857.png">

This unfortunately makes the entire PDF unreadable.

**Comment by SoniaLopezBravo** [comment]
@tcNickolas @cgranade Is there any way this can be fixed? Thanks!

**Comment by Bradben** [comment]
Unfortunately, no. This is a known issue - it is a limitation of PDF conversion tool that Docs uses.

**Comment by SoniaLopezBravo** [comment]
Thank you @Bradben !

**Comment by filipw** [comment]
is there an upstream issue tracking this? that is a pretty unfortunate limitation.
after all, PDF generation could be done in a way that MathJax renders correctly (e.g. by passing through a headless browser).
