### ISSUE TITLE
Cannot link to quickstarts for quantum computing

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs#355]
The "Quantum computing ‣ Azure Quantum ‣ Quickstarts" heading under the TOC does not have a root page that can be linked to independent of a particular quickstart:

![image](https://user-images.githubusercontent.com/31516/135006507-aade9450-7b26-485a-9473-8beb6d6eaec1.png)

This makes it hard to direct users from outside the docs to where they can find options for working with various languages and platforms.

**Comment by SoniaLopezBravo** [comment]
Since we have recently added new quickstarts, we should create an index for this section.  I have created a work item in DevOps [User Story #1882101](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1882101).

**Comment by cjgronlund** [comment]
@cgranade  - it's important we don't create pages that act as "middle-ware." They hurt the performance of the overall doc set and add upkeep with little value. You can see the results of the index strategy in the SQL Server docs which are bloated and hard to maintain. 

Let's take a look at the organic search experience, and not focus on the TOC. 
* I recommend to Sonia that she add x-links to this article: https://docs.microsoft.com/en-us/azure/quantum/concepts-circuits
* And then link to the circuits concept article from the individual circuit quickstarts.
