### ISSUE TITLE
The list of open source repositories is outdated

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs#357]
We had multiple new repositories added since this page was last updated, so it makes sense to update the page.
Two repos I know of are:
* https://github.com/microsoft/quantum-viz.js
* https://github.com/microsoft/qdk-python

There might be more; need to follow up with the team to track down every repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462770d2-93e5-8aa7-5aed-3ca00816b38a
* Version Independent ID: 080d4d40-41e2-2da2-137e-3afcaa5a1672
* Content: [Contributing to the Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/contributing-overview)
* Content Source: [articles/contributing-overview.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/contributing-overview.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by SoniaLopezBravo** [comment]
I was not aware of the existence of these two repos. Do we have any sort of database which collects the active repositories?

**Comment by tcNickolas** [comment]
Fixed via https://github.com/MicrosoftDocs/quantum-docs-private/pull/710.
