### ISSUE TITLE
The provider-specific format example is not VS Code friendly

### ISSUE THREAD

**Issue by viktorveis** [MicrosoftDocs/quantum-docs#360]
1. This snippet doesn't print results:
```
results = job.get_results()
results
```
The seconds ```result``` should be wrapped with print()

2. ```%matplotlib inline``` isn't valid in VS Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73cb1ff5-4460-2c01-d55c-e24ba98bfae6
* Version Independent ID: 2158cd2b-59ba-253d-4f14-27089d65bb55
* Content: [Submit provider-formatted quantum circuits to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-microsoft-provider-format)
* Content Source: [articles/quickstart-microsoft-provider-format.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-microsoft-provider-format.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @guenp
* Microsoft Alias: **guenp**

**Comment by SoniaLopezBravo** [comment]
Work item created in DevOps [User Story #1882857](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1882857)
