### ISSUE TITLE
Code snippets in Cirq quickstart are not VS Code friendly

### ISSUE THREAD

**Issue by viktorveis** [MicrosoftDocs/quantum-docs#361]
The following code snippets should we wrapped with print():

```
service.targets()
```

```
...
circuit
```

```
job.status()
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f7db3b-1759-1bb9-7bd8-a9555fe002fb
* Version Independent ID: 527063be-7a07-2cb7-a75d-01bd70d31b19
* Content: [Submit Cirq quantum circuits to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-microsoft-cirq)
* Content Source: [articles/quickstart-microsoft-cirq.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-microsoft-cirq.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @guenp
* Microsoft Alias: **guenp**

**Comment by SoniaLopezBravo** [comment]
Work item created in DevOps User Story [#1882857](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1882857)
