### ISSUE TITLE
Using a space after name of callable in declaration should be part of the style guide

### ISSUE THREAD

**Issue by swernli** [MicrosoftDocs/quantum-docs#396]
Currently, the style guide does not specify whether a declaration of a callable should use a space after the name or not, and in fact all the examples in the style guide do not use a space while the majority of our code in the libraries and samples does use a space. In particular, using the `CNOT` example from the style guide, this
```qsharp
operation CCNOT(control0 : Qubit, control1 : Qubit, target : Qubit)
is Adj + Ctl {
    Controlled X([control0, control1], target);
}
```
would be written instead as
```qsharp
operation CCNOT (control0 : Qubit, control1 : Qubit, target : Qubit)
is Adj + Ctl {
    Controlled X([control0, control1], target);
}
```

This aids in readability and differentiating callable declarations from callable invocations, which are specifically listed in the style guide as not using a space, ie `let r = M(q);` and not `let r = M (q);`.

Having this in the style guide would clear the way for adding it to the formatting tool that is in development.

@cgranade @ScottCarda-MS @samarsha @tcNickolas 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9fcca6-76bd-468b-c388-952832e4b5e3
* Version Independent ID: dd1ca9b0-6388-bf2e-ad0d-75e80d30390a
* Content: [Q# Style Guide - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/contributing-style-guide?tabs=guidance)
* Content Source: [articles/contributing-style-guide.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/contributing-style-guide.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by cgranade** [comment]
I'll admit, I generally find the extra space in declarations distracting, personally.

More generally, though, the style guide has thus far aimed to be more prescriptive about names and other issues of semantic style than about syntax, but it could be good to start nailing down exactly these kinds of issues as you suggest.

**Comment by ScottCarda-MS** [comment]
I really want consistency out of this either way. I would prefer to have no space in the signatures to make them consistent with the calls in the language and to make them consistent with how I think most other languages and programmers expect. But I'm fine with having the space in the signatures so long as that doesn't inspire people to put spaces in the calls.

**Comment by ScottCarda-MS** [comment]
It is also particularly awkward to see a space in a signature immediately following an attribute which doesn't use the space:
```qsharp
@EntryPoint()
    operation HelloQ () : Unit {
        Message("Hello quantum world!");
    }
```

**Comment by swernli** [comment]
For the difference between the `EntryPoint` attribute and the declaration, I see that as the same as the difference between an invocation and a declaration. The attribute is more akin to an invocation in my mind.

**Comment by cgranade** [comment]
> For the difference between the `EntryPoint` attribute and the declaration, I see that as the same as the difference between an invocation and a declaration. The attribute is more akin to an invocation in my mind.

To be fair, it is _literally_ an invocation of the type constructor function for the attribute UDT, so that's consistent there!

**Comment by cgranade** [comment]
[§Formatting conventions](https://docs.microsoft.com/azure/quantum/contributing-style-guide?tabs=guidance#formatting-conventions) is currently a bit thin, in any case, reflecting the above priority of semantic consistency (e.g.: operations do things / functions are things, using currying order for inputs), but we do have some coverage there for this issue:

![image](https://user-images.githubusercontent.com/31516/141556244-8cc6d882-6aeb-43d6-87b0-67e9657f2722.png)

**Comment by swernli** [comment]
My reading of that guidance had been that it applies to invocations and not declarations, but looking at it again it could easily be seen as a blanket statement that covers both. Was that the intent?

**Comment by swernli** [comment]
To that end, the examples that go along with the guidance show an invocation and not a declaration.

**Comment by samarsha** [comment]
I can't see how that sentence as written could apply to calls but not declarations, since the space in a declaration also occurs "after [a] function, operation, or UDT name" (the name of the declared callable).

**Comment by ScottCarda-MS** [comment]
I agree that the rule as written does not make a distinction between calls and declarations. Maybe instead of updating the rules to reflect how we have written the samples/libraries, we should update the samples/libraries to reflect this broader interpretation of the rule. We could also add code examples in these rules to really clarify what it means.

**Comment by swernli** [comment]
Yeah, I think an example here would help clarify. As it is, the examples make it seem to me like it is specific to invocations, when it sounds like everyone else sees this as applying across the board:
![image](https://user-images.githubusercontent.com/10567287/142493368-39f5e837-07e7-4968-9f75-966cdd58f5f3.png)

**Comment by SoniaLopezBravo** [comment]
After reading through this conversation, I'm having a hard time coming to the final conclusion. Do we or do we not need to specify that a declaration of a callable should use a space?

**Comment by swernli** [comment]
@SoniaLopezBravo I think the conclusion we came to was that declarations should not have a space between the name and the open parenthesis.
