### ISSUE TITLE
missing commandline step

### ISSUE THREAD

**Issue by HjoshM** [MicrosoftDocs/quantum-docs#439]
The steps listed below "**[Optional] Create a solution for both projects**" are missing `cd ..` because first you have to exit the host directory (i.e. go one level back up) and then run those three commands. Please add the `cd ..` step at the top.

---
#### Детаљи документа

⚠ *Не уређујте ову секцију. Она је неопходна за повезивање проблема слиједом docs.microsoft.com ➟ GitHub.*

* ID: 2ef8b295-7ecb-b6d6-5e7a-95585e4f24ba
* Version Independent ID: 287c02fe-8d56-06d4-26b5-c3a09635c4c9
* Content: [Develop with Q# and .NET - Azure Quantum ](https://docs.microsoft.com/bs-cyrl-ba/azure/quantum/install-csharp-qdk?tabs=tabid-cmdline%2Ctabid-csharp)
* Content Source: [articles/install-csharp-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-csharp-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by dphansen** [comment]
Thank you for your contribution. This has been fixed and will be published soon.
