### ISSUE TITLE
Small error in ionQ demo

### ISSUE THREAD

**Issue by rryoung98** [MicrosoftDocs/quantum-docs#465]
The following code in the estimating job cost 
```
target = IonQ(workspace=workspace, name="ionq.qpu")
cost = target.estimate_cost(circuit, num_shots=500)

print(f"Estimated cost: {cost.estimated_total}")
```
should be

```
target = workspace.get_targets(workspace=workspace, name="ionq.qpu")
cost = target.estimate_cost(circuit, num_shots=500)

print(f"Estimated cost: {cost.estimated_total}")
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73cb1ff5-4460-2c01-d55c-e24ba98bfae6
* Version Independent ID: 2158cd2b-59ba-253d-4f14-27089d65bb55
* Content: [Submit provider-formatted quantum circuits to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-microsoft-provider-format?pivots=platform-quantinuum)
* Content Source: [articles/quickstart-microsoft-provider-format.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-microsoft-provider-format.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @guenp
* Microsoft Alias: **guenp**

**Comment by rryoung98** [comment]
I can just change it

**Comment by SoniaLopezBravo** [comment]
Hi @rryoung98 
Thank you for your feedback, and sorry for the delay response. We´ll fix that.
