### ISSUE TITLE
Some equation blocks not rendering

### ISSUE THREAD

**Issue by m1c0l** [MicrosoftDocs/quantum-docs#471]
Under the "Density operator" section, the first and third equation blocks are not rendering properly:
![image](https://user-images.githubusercontent.com/9160756/152472004-c45517a4-92e2-4e68-a68d-bf1e00045ac2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c36178-f48a-d961-021d-0f567b71a853
* Version Independent ID: e7c36178-f48a-d961-021d-0f567b71a853
* Content: [Open systems - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/concepts-open-systems)
* Content Source: [articles/concepts-open-systems.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/concepts-open-systems.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @cjgronlund
* Microsoft Alias: **cgronlun**

**Comment by SoniaLopezBravo** [comment]
Hi @m1c0l, thank you for your feedback. We´ll take care of that

**Comment by SoniaLopezBravo** [comment]
Solved in https://github.com/MicrosoftDocs/quantum-docs-private/pull/777
