### ISSUE TITLE
QC job API docs appear in optimization and not in Python SDK browser

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs#484]
The API reference for QC jobs appears to be published to https://docs.microsoft.com/azure/quantum/optimization-job-reference#jobdetails, under the optimization section of the conceptual documentation for the Azure Quantum service, QDK, etc. docset:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31516/157311115-227de67a-f1c6-4530-a544-7391bc9fc616.png">

I would expect Python API references for QC services to made available via the [Python API browser](https://docs.microsoft.com/python/api), rather than in conceptual documentation for QIO workflows, but at the moment only `azure.mgmt.quantum` APIs are available in the API browser:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/31516/157311371-ec1f21da-95f5-4280-90aa-3f415bc7925d.png">

**Comment by Bradben** [comment]
Issue being addressed in work item - https://dev.azure.com/msft-skilling/Content/_queries/edit/58630/?triage=true
