### ISSUE TITLE
Submit Cirq add Target

### ISSUE THREAD

**Issue by cleschack** [MicrosoftDocs/quantum-docs#485]
Had an issue with running: result = service.run(program=circuit, repetitions=100) as per Submit Cirq Quantum Page.

Needed to provide target: result = service.run(program=circuit, repetitions=100, target="ionq.simulator"). That seemed to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f7db3b-1759-1bb9-7bd8-a9555fe002fb
* Version Independent ID: 527063be-7a07-2cb7-a75d-01bd70d31b19
* Content: [Submit Cirq quantum circuits to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-microsoft-cirq?pivots=platform-ionq)
* Content Source: [articles/quickstart-microsoft-cirq.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-microsoft-cirq.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @guenp
* Microsoft Alias: **guenp**

**Comment by SoniaLopezBravo** [comment]
Hi @cleschack ! Thank you for submitting this. 

I know this is optional, but did you specified a default target when creating this service object that connects to your Azure Quantum workspace? 
```
service = AzureQuantumService(
    resource_id="",
    location="",
    default_target="ionq.simulator"
)
````

**Comment by SoniaLopezBravo** [comment]
Closing this issue as I tried to reproduce it following steps in documentation, and didn´t run into any error. If one specified default target, job should run successfully.
