### ISSUE TITLE
Bonsai Link at bottom of article is irrelevant?

### ISSUE THREAD

**Issue by lwoodyiii** [MicrosoftDocs/quantum-docs#518]
At the bottom of the article there is a link to Bonsai, but I don't see how it applies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f29e0e-bc41-bcd5-6c59-d661a60b189a
* Version Independent ID: 5fc05205-d317-51e8-08fd-f61caa0cf007
* Content: [Using a service principal to authenticate - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/optimization-authenticate-service-principal)
* Content Source: [articles/optimization-authenticate-service-principal.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/optimization-authenticate-service-principal.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @anraman
* Microsoft Alias: **anraman**

**Comment by SoniaLopezBravo** [comment]
@lwoodyiii I am afraid I´m missing the link. What paragraph is it in?
