### ISSUE TITLE
A wrong value in page named immutability

### ISSUE THREAD

**Issue by weucode** [MicrosoftDocs/quantum-docs#525]
I think there is a mistake in the following statement.

> The last line makes use of the abbreviated syntax for [[evaluate-and-reassign statements](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/statements/variabledeclarationsandreassignments#evaluate-and-reassign-statements)](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/statements/variabledeclarationsandreassignments#evaluate-and-reassign-statements), and could equivalently have been written as `set arr1 = arr1 w/ 0 <- 1;`.

Probably the equivalent content is `set arr1 = arr1 w/ 0 <- 3;`.Is this right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf43f883-f508-f483-dbf5-871902b02085
* Version Independent ID: 5ab49b64-ad9b-2f5c-5a96-a72067f498df
* Content: [Immutability in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/typesystem/immutability#immutability)
* Content Source: [articles/user-guide/language/TypeSystem/immutability.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/TypeSystem/immutability.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
Hi @weucode! Thanks for pointing this out, you are totally right. We will fix this asap.

**Comment by weucode** [comment]
It's my pleasure.
