### ISSUE TITLE
Unable to run Quantum Python sample programs

### ISSUE THREAD

**Issue by tsayankar** [MicrosoftDocs/quantum-docs#534]
[Enter feedback here]

Hello, I am trying to run sample programs in Python but I get this error. Need quick help to resolve this issue.
----------------
(qsharp-env) C:\Users\xyz\OneDrive - Microsoft\xyz\Innovations\Proactive voice assistant\code\Quantum-env-test>python quantum-env-test.py
Preparing Q# environment...
C:\Users\xyz\Anaconda3\envs\qsharp-env\lib\site-packages\nest_asyncio.py:119: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  handle._run()
Traceback (most recent call last):
  File "C:\Users\xyz\OneDrive - Microsoft\V-xyz\Innovations\Proactive voice assistant\code\Quantum-env-test\quantum-env-test.py", line 2, in <module>
    from HostPython import SayHello
ModuleNotFoundError: No module named 'HostPython'
-----------------
Thanks,
Tushar
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2a2b-76ba-f5a2-2eba-c2878d300fea
* Version Independent ID: 48a7a218-babc-7e50-5b4e-83c91144ea7c
* Content: [Set up a Q# and Python environment - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-python-qdk?tabs=tabid-conda)
* Content Source: [articles/install-python-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-python-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by Bradben** [comment]
@tsayankar - Thanks for reporting this issue. We have a bug filed and will try to resolve this as soon as possible.

**Comment by Bradben** [comment]
Resolved in https://github.com/microsoft/iqsharp/issues/645
