### ISSUE TITLE
Code snippet is incorrect - should have no namespace

### ISSUE THREAD

**Issue by giobb** [MicrosoftDocs/quantum-docs#54]
The code snippet is different and incorrect. Having namespace is not allowed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8211e174-4283-67f1-4c94-3a18ca177382
* Version Independent ID: 775b48ad-8cd3-3411-b5ea-8020df9d9e54
* Content: [Develop with Q# Jupyter notebooks - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-jupyter-qkd?tabs=tabid-conda&source=docs)
* Content Source: [articles/install-jupyter-qkd.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-jupyter-qkd.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hi @giobb, 
Thanks for your feedback.  You are right, the depicted code snippet in step 2 doesn't correspond to Jupyter notebook. In Q# Jupyter notebooks, code is automatically wrapped in a namespace, so there is no need to declare one. 
We will update that as soon as possible.
