### ISSUE TITLE
/user-guide/machines/resources-estimator moved without redirect

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs#541]
It appears as though the URL https://docs.microsoft.com/azure/quantum/user-guide/machines/resources-estimator returns a 404, with the content having been moved to https://docs.microsoft.com/azure/quantum/machines/resources-estimator. The lack of a redirect, however, has broken a number of links across the Quantum Development Kit. If it'd be possible to quickly add that redirect to restore builds and link checks, that'd be greatly appreciated. Thanks!

**Comment by SoniaLopezBravo** [comment]
Thanks for noticing and sorry for the inconvenience. We will take care of that right away!
