### ISSUE TITLE
"Access modifiers" link in "Callable declarations" page seems to be broken

### ISSUE THREAD

**Issue by jond01** [MicrosoftDocs/quantum-docs#545]
The page about [Callable declarations](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/programstructure/callabledeclarations#callable-declarations) contains the following "Access modifiers" link:
https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/programstructure/#access-modifiers
This link directs to a page that does not mention the topic.
It would be helpful to fix the link.

The section below seems to be related but probably not entirely covering the topic:
https://docs.microsoft.com/en-us/azure/quantum/contributing-style-guide?tabs=guidance#private-or-internal-names

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379f3160-17c7-ec40-6bb0-eb28cbd60731
* Version Independent ID: 3af2151e-c794-064d-d91f-203af79a9de8
* Content: [Callable Declarations in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/programstructure/callabledeclarations#feedback)
* Content Source: [articles/user-guide/language/ProgramStructure/callabledeclarations.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/ProgramStructure/callabledeclarations.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
Hi @jond01 ! Thank you so much for pointing this out. We will fix this as soon as possible.

**Comment by SoniaLopezBravo** [comment]
@bettinaheim can you help on this one? It seems that "Callable declarations" article is missing
