### ISSUE TITLE
deprecated syntax in the doc for copy-and-update

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs#547]
The syntax `mutable arr = new Int[3];` is flagged as deprecated by VSCode.
VSCode advises to use `mutable arr = [x, size = n];` instead to initialize arr with n times the value x. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b618cd8-0cb8-745c-50f6-116a73819d17
* Version Independent ID: 384b7adc-ea4f-cdff-2193-6cd208a87d53
* Content: [Copy-and-update expressions in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/copyandupdateexpressions#copy-and-update-expressions)
* Content Source: [articles/user-guide/language/Expressions/copyandupdateexpressions.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Expressions/copyandupdateexpressions.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
Hi @vivienlonde ! Thank you for pointing this out. We will fix this as soon as possible.
