### ISSUE TITLE
Target documentation misrepresents support for job types on different targets

### ISSUE THREAD

**Issue by Mobius5150** [MicrosoftDocs/quantum-docs#55]
[Our current documentation on targets](https://docs.microsoft.com/en-us/azure/quantum/concepts-targets-in-azure-quantum) does a very poor job of explaining the two types or jobs and targets that we support. We've had several folks come away with the impression that Q# jobs may be run on optimization targets.

This doc needs to be restructured for clarity and to give sufficient weight to Optimization vs. QC.

**Comment by cgranade** [comment]
That's something I ran into a bit with instructions on the Azure Quantum service samples as well; would be good to align with how we discuss the two kinds of targets in those README.md files as well, perhaps?

**Comment by Mobius5150** [comment]
Agreed we should absolutely align on the right definitions. I also think the existing article has a structural issue because the first sections is about quantum devices, and says " your Q# code can run seamlessly on all of the Azure Quantum targets.". I'd propose a structure like:

- Targets in Azure Quantum
  - Optimization Solvers
  - Quantum Computing targets

Then we could have a link to the relevant target type in README files. would that help with what you'd like to address?

**Comment by cgranade** [comment]
> Then we could have a link to the relevant target type in README files. would that help with what you'd like to address?


I think that could be really helpful, yeah. At the moment, there's no link I can provide from the READMEs that helps explain why some of the targets listed by `az quantum target list` cannot be used to run Q# applications; your suggestion would really help with that, I think.

**Comment by geduardo** [comment]
Yes, we need to restructure the article. I'll do it.

**Comment by Mobius5150** [comment]
@cgranade I'd also like to see us outputting the target type in `az quantum target list`. Will see if we have a product backlog item for that.

**Comment by geduardo** [comment]
I created a PR to address this issue: #59

Please, review and add your suggestions.
