### ISSUE TITLE
az quantum job output needs a job-id parameter instead of id

### ISSUE THREAD

**Issue by ashwinmayya** [MicrosoftDocs/quantum-docs#555]
The documentation shows **id** as a parameter for the az quantum job output command
az quantum job output -id yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy -o table

However, using id fails. The actual parameter expected is **--job-id** or **-j** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bea049b-35e3-72ed-ea80-71a7968e7e12
* Version Independent ID: ec461880-8ee8-d258-7283-62bfd65ca1a7
* Content: [Submit Q# jobs to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs?pivots=ide-azurecli)
* Content Source: [articles/how-to-submit-jobs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-submit-jobs.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @Bradben
* Microsoft Alias: **sonialopez**

**Comment by Bradben** [comment]
Thanks for submitting this issue. The issue has been addressed and the docs are being updated.
