### ISSUE TITLE
A misuse of `:` as terminal character 

### ISSUE THREAD

**Issue by weucode** [MicrosoftDocs/quantum-docs#561]
Here is a wrong terminal character in line 5.

```
newtype TwoStrings = (str1: String, str2: String);

operation LinkTwoStrings(str : TwoStrings) : String {
    let s1 = str::str1;
    let s2 = str::str2:
    return s1 + s2;
}
```

If run this fragment, the following error message will be given.

> error QS3035: Unexpected code fragment.

# Environment

operating system : Windows 10

dotnet version : 6.0.301

QDK : 0.25.218240

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b76f2d-ea42-8fb5-d2bf-f40de79cac37
* Version Independent ID: e25b13ab-1ac2-c8dd-927d-3384f8de1211
* Content: [Item access in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/itemaccessexpressions#feedback)
* Content Source: [articles/user-guide/language/Expressions/itemaccessexpressions.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Expressions/itemaccessexpressions.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by SoniaLopezBravo** [comment]
Hi @weucode ! Thank you for pointing this out. We will address this typo asap :)

**Comment by Bradben** [comment]
Fixed in https://github.com/microsoft/qsharp-language/pull/156
