### ISSUE TITLE
Title should be "resource estimator". Note that the TOC and the article dont match

### ISSUE THREAD

**Issue by SerinaKaye** [MicrosoftDocs/quantum-docs#564]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53f218b-929a-66f9-b18f-9062b3f4d8c8
* Version Independent ID: a53f218b-929a-66f9-b18f-9062b3f4d8c8
* Content: [Quantum resources estimator - Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/machines/resources-estimator)
* Content Source: [articles/machines/resources-estimator.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/machines/resources-estimator.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
Hi @SerinaKaye! Note that heading, metadata title and TOC title don't always match. In this case, the heading expands the TOC title implying that the resource estimator is part of the QDK extension.
