### ISSUE TITLE
Mac Q# local run

### ISSUE THREAD

**Issue by AlbertPhelps** [MicrosoftDocs/quantum-docs#567]
[How to configure this for Mac/ VS Code?]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2a2b-76ba-f5a2-2eba-c2878d300fea
* Version Independent ID: 48a7a218-babc-7e50-5b4e-83c91144ea7c
* Content: [Set up a Q# and Python environment - Azure Quantum ](https://learn.microsoft.com/en-gb/azure/quantum/install-python-qdk?tabs=tabid-conda)
* Content Source: [articles/install-python-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-python-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by Bradben** [comment]
Hi Albert - was there a specific issue or problem that you are running into? Any details will help, thanks!

**Comment by AlbertPhelps** [comment]
Hi  there, I'm trying to run locally with vs code following the tutorial and can install the qdk fine and have qsharp as an input option.

However I can't seem to get the kernel to run the code installed properly and thought it might be as I've an ARM Mac? It seems to be throwing that type of error

I will share a screenshot of the error when back at my desk

Albert


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bradben ***@***.***>
Sent: Monday, October 10, 2022 11:59:35 PM
To: MicrosoftDocs/quantum-docs ***@***.***>
Cc: Phelps, Albert ***@***.***>; Author ***@***.***>
Subject: [External] Re: [MicrosoftDocs/quantum-docs] Mac Q# local run (Issue #567)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Hi Albert - was there a specific issue or problem that you are running into? Any details will help, thanks!

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MicrosoftDocs_quantum-2Ddocs_issues_567-23issuecomment-2D1273891483&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oetYpqkV1_W7qW3Gc-3xDuCX8vVcDYfMkA3biFZFBok&m=9wNx4j2K2Scm2Qo8LSzHjdu0aTavBFZk5K4HaCRFSB6fYM7fin7grAVJdFRxtlr6&s=E0K67zWJFC8FFrXaWfPbFDYed43w46wUIM0UIZVEsP8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AV6H2HXFFTEY2USQJTMZ7NTWCSNVPANCNFSM6AAAAAAQ7E7JJ4&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oetYpqkV1_W7qW3Gc-3xDuCX8vVcDYfMkA3biFZFBok&m=9wNx4j2K2Scm2Qo8LSzHjdu0aTavBFZk5K4HaCRFSB6fYM7fin7grAVJdFRxtlr6&s=MeLdYTuFar-onKMKCgbpGo6DMs1W0iQIZOMyU_mdDeQ&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the email by you is prohibited.

**Comment by Bradben** [comment]
Closing due to no response. Please reopen the issue if you encounter the error again. Thanks!
