### ISSUE TITLE
Inaccuracy in description of entanglement in Quantum computing / Overview / Understanding Quantum computing

### ISSUE THREAD

**Issue by amorphedstar** [MicrosoftDocs/quantum-docs#575]
The sentence
```Two systems are entangled when the state of the global system cannot be written as a linear combination of the subsystems.```
is incorrect and should probably read more like
```Two systems are entangled when the state of the global system cannot be written as a tensor product of states of the subsystems.```
The "Note" box in the same section is also a bit misleading. If we are considering pure 2-bit states, then two qubits _are_ correlated only if they are entangled, and two classical bits have definite values, so it doesn't make sense to talk about their correlation. But if we are considering mixed states, where there are different probabilities of being in several different pure states, then there is no difference in possible probability distributions (or correlations) between measurements on the quantum system, or on suitably randomized classical bit states. The difference isn't between correlations in the statistical sense, but rather in the fact that certain qubits can interfere with themselves when performing certain operations on entangled (pure) states. If you were thinking of Bell's inequality, the comparison still does not make sense because it depends on measuring with respect to different bases, and classical bits are only ever 0 or 1 (or a mixed state of the two if you are ignorant).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b298a605-9585-e75a-2782-ffc63b1d6d92
* Version Independent ID: 03e8211f-a888-ec05-9190-db5d952934fb
* Content: [Understanding quantum computing - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/overview-understanding-quantum-computing)
* Content Source: [articles/overview-understanding-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/overview-understanding-quantum-computing.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
Hi @amorphedstar ! Thank you so much for your feedback. Although the documentation doesn't claim to have the level of instruction of advanced quantum computing texts, accuracy is very important to us. We'll review this article to write a more detailed version.
