### ISSUE TITLE
Add location to 1QBit quickstart docs

### ISSUE THREAD

**Issue by xinyi-joffre** [MicrosoftDocs/quantum-docs#58]
In the quickstart for 1QBit, the workspace set up uses this setup:

```python
from azure.quantum import Workspace

# Copy the settings for your workspace below
workspace = Workspace(
    resource_id = ""   # add the Resource ID of the Azure Quantum workspace you created
)
workspace.login()
```

This seems to only work for workspaces in "West US". For workspaces in other regions, when you go to submit a job, it will throw this error, which may not be clear to users that this is because West US is the default location:

> RestErrorException: (IncorrectDataplaneEndpoint) The Azure Quantum endpoint you called cannot process requests for workspaces created in 'northeurope'. Please call the correct endpoint by passing the workspace location to the client.

Should we add the location parameter to the code snippet above so that it works for all regions? Or maybe use the other format that splits the different parameters including subscription id, resource group, location etc.?

I can make the change, but just wanted to see if we had preference for using same workspace setup method across the docs, or if I should just update the snippet to have location parameter?:

```python
from azure.quantum import Workspace

# Copy the settings for your workspace below
workspace = Workspace(
    resource_id = "",   # add the Resource ID of the Azure Quantum workspace you created
    location = "North Europe" # location of the Azure Quantum workspace
)
workspace.login()
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c28090-a606-256a-d4d2-45fff1175ecc
* Version Independent ID: 3847d2bd-d17c-ecde-cd07-6ad21be9595c
* Content: [1QBit quickstart for Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/quickstart-1qbit)
* Content Source: [articles/quickstart-1qbit.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/quickstart-1qbit.md)
* Service: **azure-quantum**
* Sub-service: **optimization**
* GitHub Login: @mblouin
* Microsoft Alias: **mblouin**

**Comment by geduardo** [comment]
Thank you @xinyi-joffre for filling this issue!

@Mobius5150 @ffrachon can you take a look at this?

> Should we add the location parameter to the code snippet above so that it works for all regions? Or maybe use the other format that splits the different parameters including subscription id, resource group, location etc.?

**Comment by Mobius5150** [comment]
Yes this would be good! Are you able to make this change @xinyi-joffre or @geduardo ? 

I think it would also make sense to use the same constructor in the Microsoft and 1QBit quickstarts, and probably want to go with the `resource_id` and `location` version.

**Comment by Mobius5150** [comment]
Just reviewed @dime10 though I'm not an admin of this repo. @geduardo can you please help merge #117?
