### ISSUE TITLE
Q# package installation for VS Code: step-by-step guide is missing

### ISSUE THREAD

**Issue by wzpxq** [MicrosoftDocs/quantum-docs#585]
Hello, 

I tried to install the package Microsoft.Quantum.Numerics in VS Code with the help of https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/?tabs=tabid-csproj#installation. 

The first step "dotnet add package Microsoft.Quantum.Numerics" worked fine. 
After that, it was not entirely clear to me how to proceed for VS Code as the description continued specifically for Visual Studio. 
So I just tried "Install-Package Microsoft.Quantum.Numerics" which did not work. The error message suggested to use administrator rights to install the package in "...AppData\Local\PackageManagement\NuGet\Packages". However, this folder does not exist on my machine. 

Please update the page to show a step-by-step guide on how to install Q# packages for VS Code. If further extensions are required for that (NuGet?), please state so. Also, an explanation of what NuGet is and why it is needed would be useful. 

Best regards, 
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d836e794-b7be-9d2e-9bf7-d93f098b0f82
* Version Independent ID: 00d1863d-321a-b999-6a8a-03be2e22920a
* Content: [Quantum Development Kit Libraries - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/?tabs=tabid-csproj#installation)
* Content Source: [articles/user-guide/libraries/index.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/index.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by Bradben** [comment]
Hello Peter, 

We're sorry this impacted your install experience with Azure  Quantum, and thanks for bringing it to our attention. We'll update the install steps as needed and post an update here.

Thanks, Brad
