### ISSUE TITLE
.NET SDK needs to be downloaded as well to use the QDK

### ISSUE THREAD

**Issue by MichaelGoulding** [MicrosoftDocs/quantum-docs#587]
[Enter feedback here]
I installed VS Code on a new machine and installed the QDK.  However, I could not run the Q# sample because the .NET SDK needed to be installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab7e591-2603-064c-120c-4e47ca8a1525
* Version Independent ID: 649a7236-80b3-0cd2-558c-9ac6e1e178e1
* Content: [Set up the Quantum Development Kit - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/install-overview-qdk?tabs=tabid-vscode%2Ctabid-conda)
* Content Source: [articles/install-overview-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-overview-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by Bradben** [comment]
Hi Michael, 

Thanks for letting us know about your install issue.  Were you following the steps in [this article](https://learn.microsoft.com/en-us/azure/quantum/install-overview-qdk?tabs=tabid-vscode%2Ctabid-conda#use-q-and-python-with-visual-studio-and-visual-studio-code)?  .NET SDK is listed as a prerequisite for the VS Code and Visual Studio scenarios. If this is not your scenario, please let us know. 

Thanks,
Brad
