### ISSUE TITLE
Enter a descriptive title for your issue or suggestion

### ISSUE THREAD

**Issue by hros** [MicrosoftDocs/quantum-docs#589]
In the description of the [Draper Adder](https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/algorithms#draper-adder) there is the following formula:
$x=y+0.x_0x_2\ldots x_n$
$e^{i 2 \pi x} = e^{i 2 \pi \left( 0.x_0x_2\ldots x_{n-1} \right)}$
Is there a reason why $x_1$ is skipped and that one expression ends with $x_n$ while the other ends with $x_{n-1}$ ?

**Comment by SoniaLopezBravo** [comment]
Hi @hros. Thank you so much for reporting this. I've looked into the formulas, and you're right; there's a typo in the sub indices. It should be $x_1,x_2,...,x_n$. It'll be fixed by today.
