### ISSUE TITLE
rendering issue in Concepts / Operations on multiple qubits

### ISSUE THREAD

**Issue by haplav** [MicrosoftDocs/quantum-docs#592]
There is a rendering error in 
https://learn.microsoft.com/en-us/azure/quantum/concepts-multiple-qubits#entanglement-in-pure-states

<img width="910" alt="image" src="https://user-images.githubusercontent.com/16013816/224448295-6560cb04-9e50-42dd-9188-624a37904f0c.png">

It seems the renderer has difficulties with the `\ket{}` followed by subscript, e.g. `$\ket{\phi}_{AB}$`, from some reason.

**Comment by SoniaLopezBravo** [comment]
Hi @haplav - Thank you so much for catching this one. We'll fix the error asap.
