### ISSUE TITLE
qiskit_machine_learning - ModuleNotFoundError

### ISSUE THREAD

**Issue by karthikeyanVK** [MicrosoftDocs/quantum-docs#594]
I tried to run the code on the page in Azure Quantum workspace, and get the following error. 

`ModuleNotFoundError: No module named 'qiskit_machine_learning'`

I also installed `!pip install qiskit-machine-learning`

![image](https://user-images.githubusercontent.com/11407921/224530115-cdf7a000-049b-452b-abe0-1dace5a438fd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb056c67-eed8-4e5c-1d83-470909d85f74
* Version Independent ID: eb056c67-eed8-4e5c-1d83-470909d85f74
* Content: [Adapting Qiskit samples - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/how-to-adapt-qiskit)
* Content Source: [articles/how-to-adapt-qiskit.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-adapt-qiskit.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
Hi @karthikeyanVK - Thank you for your feedback. I tried to reproduced you error but the sample works fine for me. I assume you followed the steps in [Understanding quantum machine learning](https://learn.microsoft.com/en-us/azure/quantum/overview-quantum-machine-learning).
Did you  install qiskit in the notebook? Add a cell prior intalling quantum machine learning and copy:
`!pip install qiskit`

Let me know if the error persists.
