### ISSUE TITLE
Concepts / Operations on multiple qubits: little-endian confusion

### ISSUE THREAD

**Issue by haplav** [MicrosoftDocs/quantum-docs#597]
In #596, I actually wanted to rephrase the statement
> Let $S$ be the set of all $e_k$ such that the qubit in question takes the value $1$ for that value of $k$.

as

> Let $S$ be the set of all $e_k$ such that the given qubit has $1$ on the $k^{\rm th}$ position.

I though it was an equivalent statement just clearer.

But then it is contradicting with the little-endian representation, for example you define
$e_1\equiv 10 = [0, 0, 1, 0]^T$.

I also think $e_0, e_1, ...$ should better follow the order of basis vectors as usual in linear algebra and as typed earlier in the article:
$e_0\equiv 00 = [1, 0, 0, 0]^T,\ e_1\equiv 01 = [0, 1, 0, 0]^T,\ e_2\equiv 10 = [0, 0, 1, 0]^T,\ e_3\equiv 11 = [0, 0, 0, 1]^T$

Or do I misunderstand anything?

So I personally think that it would be better to use the big-endian convention on this page and then add a warning that the little-endian convention is also sometimes used. I can do the edits if that's agreed.

**Comment by SoniaLopezBravo** [comment]
Hi @haplav - thank you for your comment. Actually, your statement "Let $S$ be the set of all $e_k$ such that the given qubit has 1 on the $k^{k}$ position" is not equivalent to the statement in the page. 

When we say " $e_k$ such that the qubit in question takes the value 1", we mean in the computational basis, not the position in the vector state. For example, to measure the first qubit, we take the computational basis vectors with 1 in the first qubit, these states are 10 and 11. 

The order you propose for labeling the computational basis is big-endian. That labeling is also perfectly fine, and both endianness are used in quantum information theory.

**Comment by haplav** [comment]
@SoniaLopezBravo 
> When we say " $e_k$ such that the qubit in question takes the value 1"

The problem is you don't say only that. You say
> $e_k$ such that the qubit in question takes the value $1$ for that value of $k$

Maybe you could just write
>  " $e_k$ such that the $k^{\rm th}$ qubit takes the value 1"

to make it clearer and shorter?
