### ISSUE TITLE
line 2 : "intractable to simulate on quantum computers" -> intractable to simulate on classical computers 

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs#60]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778bb870-f8c3-348f-245e-d7a5f385d8f9
* Version Independent ID: 1b6a2026-3d7b-8a84-971d-4fb2242a84b6
* Content: [Introduction to the Quantum Chemistry Library - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/)
* Content Source: [articles/user-guide/libraries/chemistry/index.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/chemistry/index.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **ageller**

**Comment by geduardo** [comment]
Good catch! Thanks!
