### ISSUE TITLE
Incorrect format parameter

### ISSUE THREAD

**Issue by viktorveis** [MicrosoftDocs/quantum-docs#602]
The sample command line `GetGateCount>dotnet run -- --path=../IntegralData/YAML/h2.yaml --format=YAML` gives the following error: `Invalid value specified for format. Allowed values are: Liquid, Broombridge.` The following command line works as expected: `GetGateCount>dotnet run -- --path=../IntegralData/YAML/h2.yaml --format=Broombridge`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 171ed8dd-5477-453d-8a55-908e1f03a938
* Version Independent ID: a1309712-00fe-fa31-9e5e-869640dedfea
* Content: [Q# Chemistry Library Installation - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/installation)
* Content Source: [articles/user-guide/libraries/chemistry/installation.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/chemistry/installation.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by Bradben** [comment]
Transferred to work item https://dev.azure.com/msft-skilling/Content/_workitems/edit/89149
