### ISSUE TITLE
Info missing on how to get Templates

### ISSUE THREAD

**Issue by wzpxq** [MicrosoftDocs/quantum-docs#603]
Hi, 

I just tried to follow the instructions to create a Q# library using the command line in VS Code. 
However, "dotnet new classlib -lang Q# -o quantum" fails. 
It turns out I did not have the necessary template although the QDK was installed on my machine. 

I had to call "dotnet new -i Microsoft.Quantum.ProjectTemplates" to install the necessary template. 
I suggest you add this info to the page. This could help others. 

Best regards, 
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5e6d25a-d9bf-089d-f2e7-0b6b11959bcd
* Version Independent ID: c5e6d25a-d9bf-089d-f2e7-0b6b11959bcd
* Content: [Develop with Q# and .NET - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/how-to-csharp-qdk-local?tabs=tabid-cmdline%2Ctabid-csharp)
* Content Source: [articles/how-to-csharp-qdk-local.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-csharp-qdk-local.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by SoniaLopezBravo** [comment]
Hi @wzpxq - Thank you for reporting. You're right, I was able to reproduce your error. We'll update the documentation with the correct instructions asap.
