### ISSUE TITLE
More examples as to how Broombridge handles two-electron integrals with duplicates

### ISSUE THREAD

**Issue by christopherkang** [MicrosoftDocs/quantum-docs#604]
The current section on two-electron integrals is restricted to the case where all the i, j, k, l are the same or unique. Can the documentation be updated to include context on the case where there is some duplication? E.g., see [H2's](https://github.com/microsoft/quantum/blob/main/samples/azure-quantum/chemistry/data/broombridge/hydrogen_0.2.yaml) YAML, which includes [1, 2, 2, 1], or [caffeine's](https://github.com/microsoft/Quantum/blob/main/samples/azure-quantum/chemistry/data/broombridge/caffeine.yaml) YAML, which includes [2, 1, 1, 1], [2, 2, 1, 1], [2, 2, 2, 1], ... etc. 

What process is used to convert these individual values into the $a^\dagger_p a^\dagger_q a_r a_s$ terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0ebeb95-7304-18f0-0f9b-87c94b8f6dbb
* Version Independent ID: 75134b4f-ff66-0df4-dbca-ca3b8df56611
* Content: [Broombridge Schema Specification (ver 0.2) - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/schema/spec_v_0_2)
* Content Source: [articles/user-guide/libraries/chemistry/schema/spec_v_0_2.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/chemistry/schema/spec_v_0_2.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by SoniaLopezBravo** [comment]
Hi @christopherkang - Thanks for your feedback. I'll take a look at the current article and I'll come back to you asap with an answer.

**Comment by christopherkang** [comment]
Thanks, @SoniaLopezBravo ! Also, if possible, it would be good to get information on whether the equation in that section is correct, given the comment about the mulliken indexing convention (and corresponding equation below which is now iklj instead of ijkl
<img width="609" alt="image" src="https://github.com/MicrosoftDocs/quantum-docs/assets/42285636/38087a95-1f8b-4b2a-804e-388c49c75f21">

**Comment by SoniaLopezBravo** [comment]
Hi @christopherkang. The equation of the Hamiltonian is correct. Please note the dagger symbol in the sum and the * symbol in the integral. Both symbols denote complex conjugation. Mulliken indexing has indexes [i,k] as complex conjugate.

Regarding your other request, in cases where indices repeat like [2, 1, 1, 1], the Hamiltonian will be extracted by summing all combination of ${i,j,k,l}$ such that there are no symmetries. I've updated the article to show that kind of example. It should be live today.

**Comment by christopherkang** [comment]
Hey @SoniaLopezBravo ! Thanks for looking into it. I'm still a bit confused with the contributed answer and docs. 

For example, the $a^\dagger_2 a^\dagger_1 a_1 a_1$ term is missing its complex conjugate. And, the 2121 term in the docs corresponds with i, j, k, l, correct? But, if that's the case, then 2211 is the symmetry ikjl, which is not in the list of symmetries at the beginning of the section. 

Appreciate your help!
