### ISSUE TITLE
Specify current availability of targets for "Interactive Hybrid QC"

### ISSUE THREAD

**Issue by karltietze** [MicrosoftDocs/quantum-docs#605]
[Enter feedback here]

As of now,  Quantinuum QPUs and Rigetti support submitting Q# jobs in sessions
IonQ QPUs cannot be targetted because apparently IonQ does not translate into QIR.

Please update the documentation explicitely stating that IonQ QPUs at that time cannot be targetted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05bbe4cc-c235-5a5b-edd7-b6c6c449ba37
* Version Independent ID: 05bbe4cc-c235-5a5b-edd7-b6c6c449ba37
* Content: [Introduction to sessions - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/hybrid-computing-interactive?tabs=tabid-iqsharp)
* Content Source: [articles/hybrid-computing-interactive.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/hybrid-computing-interactive.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by Bradben** [comment]
Tracking in work item [90615](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90615)
