### ISSUE TITLE
missing Open in PrepareAndMeasureBellPair example

### ISSUE THREAD

**Issue by tobiashagge** [MicrosoftDocs/quantum-docs#609]
On https://learn.microsoft.com/en-us/azure/quantum/how-to-python-qdk-local,

the %%qsharp block that defines PrepareAndMeasureBellPair appears to need

open Microsoft.Quantum.Measurement;

So that MResetZ is available.

**Comment by SoniaLopezBravo** [comment]
Hi @tobiashagge! - Thank you so much for your feedback; you're right, the code snippet is missing the `Microsoft.Quantum.Measurement` namespace. We'll fix that as soon as possible.
