### ISSUE TITLE
Example code syntax error~

### ISSUE THREAD

**Issue by RAHEYO** [MicrosoftDocs/quantum-docs#617]
[Enter feedback here]

In the "using the depth counter" Q# code, you guys typed:
open Microsoft.Quantum.Intrinsic;

```
operation ApplySampleWithCCNOT() : Unit {
    use qubits = Qubit[3]);
    CCNOT(qubits[0], qubits[1], qubits[2]);
    T(qubits[0]);
}
```

where `use qubits = Qubit[3];` should not the paranthesis!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abf7fe9b-37bb-409a-9ee6-ac903beba74e
* Version Independent ID: abf7fe9b-37bb-409a-9ee6-ac903beba74e
* Content: [Trace simulator: Depth counter - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/machines/qc-trace-simulator/depth-counter)
* Content Source: [articles/machines/qc-trace-simulator/depth-counter.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/machines/qc-trace-simulator/depth-counter.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
Hi @RAHEYO, thanks for you contribution. You're right, there's an extra parenthesis. We'll fix it asap.
