### ISSUE TITLE
Minor typo in code on page

### ISSUE THREAD

**Issue by cspwcspw** [MicrosoftDocs/quantum-docs#627]
The second line of code on the page has a spurious `']'`
> `mutable q = []];`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fae6878f-d8b2-f0f6-6dcf-c315d839a1ca
* Version Independent ID: fae6878f-d8b2-f0f6-6dcf-c315d839a1ca
* Content: [Trace simulator: Invalidated qubits use checker - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/machines/qc-trace-simulator/invalidated-qubits-use-checker)
* Content Source: [articles/machines/qc-trace-simulator/invalidated-qubits-use-checker.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/machines/qc-trace-simulator/invalidated-qubits-use-checker.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
@cspwcspw Thanks for catching this one. We'll fix the typo asap.
