### ISSUE TITLE
Denotions are broken. Seen as \boldone

### ISSUE THREAD

**Issue by Akelyaporten** [MicrosoftDocs/quantum-docs#634]
At the page, some of the denotions are broken. Please see the attachment
<img width="593" alt="Ekran görüntüsü 2023-11-15 011934" src="https://github.com/MicrosoftDocs/quantum-docs/assets/73758889/e02941b1-40ae-41fb-8af7-be795062db80">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62270863-b11b-2a2b-f198-169596f1b423
* Version Independent ID: 7d700dfd-b9af-37a6-02ce-e66176574172
* Content: [Vectors & matrices in quantum computing - Azure Quantum ](https://learn.microsoft.com/en-us/azure/quantum/concepts-vectors-and-matrices)
* Content Source: [articles/concepts-vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/concepts-vectors-and-matrices.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @SoniaLopezBravo
* Microsoft Alias: **sonialopez**

**Comment by SoniaLopezBravo** [comment]
Hi @Akelyaporten - Thank you so much for catching this one. We'll fix it asap.
