### ISSUE TITLE
In the third Q# snippet, I think "arr contains [3,0,0]" should be "arr contains [10,0,0]"

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs#65]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b618cd8-0cb8-745c-50f6-116a73819d17
* Version Independent ID: 384b7adc-ea4f-cdff-2193-6cd208a87d53
* Content: [Copy-and-update expressions in Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/expressions/copyandupdateexpressions)
* Content Source: [articles/user-guide/language/Expressions/copyandupdateexpressions.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/language/Expressions/copyandupdateexpressions.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @bettinaheim
* Microsoft Alias: **beheim**

**Comment by geduardo** [comment]
Thanks, @vivienlonde! I created a PR to fix it. 

https://github.com/microsoft/qsharp-language/pull/85

**Comment by vivienlonde** [comment]
thanks :)
