### ISSUE TITLE
Linear algebra update: collection of issues

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs#8]
In order to facilitate the migration, I'll collect all the issues related to the linear algebra guide here in order to close them.

Issues: 

https://github.com/MicrosoftDocs/quantum-docs-pr/issues/781
https://github.com/MicrosoftDocs/quantum-docs-pr/issues/782
https://github.com/MicrosoftDocs/quantum-docs-pr/issues/829
https://github.com/MicrosoftDocs/quantum-docs-pr/issues/859
https://github.com/MicrosoftDocs/quantum-docs-pr/issues/465

**Comment by SoniaLopezBravo** [comment]
I checked all issues linked above and they are already closed. We can close this issue.

**Comment by geduardo** [comment]
I closed them to gather them here since all of them refer to the same big update of the linear algebra guide, that was postponed due to MSLearn and Azure quantum release.

**Comment by SoniaLopezBravo** [comment]
I noticed 3 out of 5 of these issues are related to tensor product's properties and our definition of it in https://docs.microsoft.com/en-us/azure/quantum/concepts-vectors-and-matrices. I'll check this article and see how we can improve it.
