### ISSUE TITLE
Redirect broken link fix

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs#82]
For tracking purpose

**Comment by Bradben** [comment]
All redirects have been updated to the new docset - PR https://github.com/MicrosoftDocs/azure-reference-other-pr/pull/696.  Merged to master, waiting to go live.

**Comment by cjgronlund** [comment]
@KittyYeungQ 
@Bradben 
Brad's PR to fix this issue was merged yesterday, so it should be live. Please reopen if there are still link issues.
