### ISSUE TITLE
Why still C# convention 

### ISSUE THREAD

**Issue by KamilJedrzejuk** [MicrosoftDocs/quantum-docs#86]
Unfortunately you're still using C# convention :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93695b8-e683-f357-7a64-6a9420641aae
* Version Independent ID: e2ac33fb-fb98-45b0-cd6c-23b3e57c0fb8
* Content: [Explore entanglement with Q# - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/tutorial-qdk-explore-entanglement)
* Content Source: [articles/tutorial-qdk-explore-entanglement.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/tutorial-qdk-explore-entanglement.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @geduardo
* Microsoft Alias: **v-edsanc**

**Comment by geduardo** [comment]
Thank you @KamilJedrzejuk for your feedback! Even if Q# shares some similarities with C#, Q# is a completely independent language. You can also use Python, C# to incorporate Q# operations into your scripts, or you can run Q# programs as standalone applications.
