### ISSUE TITLE
Expose docs for classes under Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime

### ISSUE THREAD

**Issue by Bradben** [MicrosoftDocs/quantum-docs#94]
Currently there are only three QCTraceSimulatorRuntime classes documented on the [dotnet/api pages](https://docs.microsoft.com/en-us/dotnet/api/microsoft.quantum.simulation.qctracesimulatorruntime). However, there many more public classes not documented (https://github.com/microsoft/qsharp-runtime/tree/main/src/Simulation/QCTraceSimulator).

The QCTraceSimulatorRuntime is specifically called out in the [_filter.xml file](https://github.com/MicrosoftDocs/csharp-quantum/blob/master/dotnet/xml/_filter.xml), which excludes namespaces and classes from publishing. 

- Should more, or all, of the QCTraceSimulatorRuntime classes be exposed?
- Should the other namespaces in the _filter.xml be evaluated as well?

**Comment by Bradben** [comment]
(From Bettina) The classes in that namespace are largely not intended to be public APIs, but are made public due to technical requirements imposed by assembly boundaries. From that perspective, we should likely not expose everything, but make sure only those public APIs that are directly user-facing should be exposed.

**Comment by geduardo** [comment]
Then I think we can close this, right? 
@Bradben
