### ISSUE TITLE
Azure CLI toc updates

### ISSUE THREAD

**Issue by TimShererWithAquent** [MicrosoftDocs/quantum-docs#96]
This is about [1828380](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1828380). 

Per email from @Bradben 

Can you add the following lines to the toc under Reference:

- name: Azure CLI
  href: /cli/azure/ext/quantum/quantum

Thanks for your help.

@dbradish-microsoft for awareness.

**Comment by Bradben** [comment]
Fixed in[ PR #278](https://github.com/MicrosoftDocs/quantum-docs-private/pull/278)

**Comment by dbradish-microsoft** [comment]
@Bradben, thank you!
